-- Import 'Nove firmy' do st.CRM_Kontakt (DB_EC) — obchodnik Pavel Zeman (ZamID 481)
-- Generoval Claude 15.6.2026. ID je IDENTITY (negeneruje se). Dedup podle FirmaText.
SET NOCOUNT ON;
BEGIN TRAN;

IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'GT Abwicklungsgesellschaft GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'GT Abwicklungsgesellschaft GmbH',N'49-71134050',N'info@gehring-group.com',N'http://www.gehring-group.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Gehringstr. 28, 73760 Ostfildern, Baden-Württemberg, Německo | Obrat: 77 086 533 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Schumag Aktiengesellschaft')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Schumag Aktiengesellschaft',N'49-2408120',N'info@schumag.de',N'http://www.schumag.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Nerscheider Weg 170, 52076 Aachen, Nordrhein-Westfalen, Německo | Obrat: 51 191 002 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Arthur Klink GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Arthur Klink GmbH',N'49-723158060',N'info@arthur-klink.de',N'http://www.arthur-klink.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Steinenlandstr. 1-7, 75181 Pforzheim, Baden-Württemberg, Německo | Obrat: 23 799 999 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Alzmetall GmbH & Co . KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Alzmetall GmbH & Co . KG',N'49-8621880',N'info@alzmetall.com',N'http://www.alzmetall.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Harald-Friedrich-Str. 2-8, 83352 Altenmarkt a.d.Alz, Bayern, Německo | Obrat: 39 900 002 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'DATRON AG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'DATRON AG',N'49-6154637660',N'info@datron.de',N'http://www.datron.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Am Innovationsfeld 1, 64372 Ober-Ramstadt, Hessen, Německo | Obrat: 60 203 949 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'WTO Werkzeug - Einrichtungen GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'WTO Werkzeug - Einrichtungen GmbH',N'49-780393920',N'info@wto.de',N'http://www.wto-tools.com',N'Matthias Sutter — Einkaufsleiter',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Neuer Hohdammweg 1, 77797 Ohlsbach, Baden-Württemberg, Německo | Obrat: 59 824 593 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Hedelius Maschinenfabrik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Hedelius Maschinenfabrik GmbH',N'49-593198190',N'info@hedelius.de',N'http://www.hedelius.de',N'Frauke — EinkäUfer',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Sandstr. 11, 49716 Meppen, Niedersachsen, Německo | Obrat: 71 365 326 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Waldrich Siegen Werkzeugmaschinen Gesellschaft mit beschränkter Haftung')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Waldrich Siegen Werkzeugmaschinen Gesellschaft mit beschränkter Haftung',N'49-2716906600',N'info@waldrichsiegen.de',N'http://www.waldrichsiegen.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Eisenhüttenstr. 21, 57074 Siegen, Nordrhein-Westfalen, Německo | Obrat: 45 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Bystronic Maschinenbau GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Bystronic Maschinenbau GmbH',N'49-36213830',N'info.bending@bystronic.com',N'http://www.bystronic.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Mühlhäuser Str. 3, 99867 Gotha, Thüringen, Německo | Obrat: 41 250 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Schirmer Maschinen GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Schirmer Maschinen GmbH',N'49-524692130',N'info@schirmer-maschinen.com',N'http://www.schirmer-maschinen.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Stahlstr. 25+29, 33415 Verl, Nordrhein-Westfalen, Německo | Obrat: 76 940 453 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Sauter Feinmechanik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Sauter Feinmechanik GmbH',N'49-71239260',N'info@sauter-feinmechanik.com',N'http://www.sauter-feinmechanik.com',N'Theofanis Papageorgiadis — Strategischer Einkäufer',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Carl-Zeiss-Str. 7, 72555 Metzingen, Baden-Württemberg, Německo | Obrat: 46 170 078 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Starrag Technology GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Starrag Technology GmbH',N'49-2166454251',N'',N'http://www.starrag.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Hugo-Junkers-Str. 12-32, 41236 Mönchengladbach, Nordrhein-Westfalen, Německo | Obrat: 47 862 431 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Klemm Bohrtechnik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Klemm Bohrtechnik GmbH',N'49-27617050',N'info@klemm.de',N'http://www.klemm.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Wintersohler Str. 5, 57489 Drolshagen, Nordrhein-Westfalen, Německo | Obrat: 61 457 321 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Peiseler GmbH & Co. KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Peiseler GmbH & Co. KG',N'49-21919130',N'peiseler.rs@peiseler.de',N'http://www.peiseler.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Morsbachtalstr. 1-3, 42855 Remscheid, Nordrhein-Westfalen, Německo | Obrat: 27 200 001 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Spinner Werkzeugmaschinenfabrik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Spinner Werkzeugmaschinenfabrik GmbH',N'49-81048030',N'sales@spinner.eu.com',N'http://spinner.eu.com',N'Jürgen Wohlers — Einkäufer',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Rudolf-Diesel-Ring 24, 82054 Sauerlach, Bayern, Německo | Obrat: 72 340 485 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Adelbert Haas GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Adelbert Haas GmbH',N'49-742533710',N'info@ahaas.com',N'http://www.ahaas.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Adelbert-Haas-Str. 1, 78647 Trossingen, Baden-Württemberg, Německo | Obrat: 58 335 934 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'TBT Tiefbohrtechnik GmbH + Co')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'TBT Tiefbohrtechnik GmbH + Co',N'49-71239760',N'info@tbt.de',N'http://www.tbt.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Siemensstr. 1, 72581 Dettingen an der Erms, Baden-Württemberg, Německo | Obrat: 50 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'GNA Abwicklungsgesellschaft GmbH & Co. KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'GNA Abwicklungsgesellschaft GmbH & Co. KG',N'49-34457630',N'info@gehring-naumburg.de',N'http://www.gehring-group.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Mariengasse 5, 06618 Naumburg (Saale), Sachsen-Anhalt, Německo | Obrat: 12 474 803 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Maschinenfabrik Herkules Meuselwitz GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Maschinenfabrik Herkules Meuselwitz GmbH',N'49-3448830',N'mhm@herkules-machinetools.com',N'http://www.herkules-machinetools.d',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Industriepark Nord, 04610 Meuselwitz, Thüringen, Německo | Obrat: e 30 660 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'transfluid Maschinenbau GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'transfluid Maschinenbau GmbH',N'49-297297150',N'info@transfluid.de',N'http://www.transfluid.net',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Hünegräben 17-24, 57392 Schmallenberg, Nordrhein-Westfalen, Německo | Obrat: 33 450 001 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'KADIA Produktion GmbH + Co.')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'KADIA Produktion GmbH + Co.',N'49-702260060',N'info@kadia.de',N'http://www.kadia.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Fabrikstr. 2, 72622 Nürtingen, Baden-Württemberg, Německo | Obrat: 28 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Gehring Technologies GmbH + Co. KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Gehring Technologies GmbH + Co. KG',N'49-71134050',N'info.eu@gehring-group.com',N'http://www.gehring-group.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Gehringstr. 28, 73760 Ostfildern, Baden-Württemberg, Německo | Obrat: 25 480 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Heinz Berger Maschinenfabrik GmbH & Co. KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Heinz Berger Maschinenfabrik GmbH & Co. KG',N'49-202247420',N'info@bergergruppe.de',N'http://www.bergergruppe.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Kohlfurther Brücke 69, 42349 Wuppertal, Nordrhein-Westfalen, Německo | Obrat: 25 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Lindenmann GmbH + Co Präzisionsfertigung KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Lindenmann GmbH + Co Präzisionsfertigung KG',N'49-730496960',N'info@lindenmann.de',N'http://www.lindenmann.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Hülenweg 33-35, 89134 Blaustein, Baden-Württemberg, Německo | Obrat: 40 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Buderus - Schleiftechnik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Buderus - Schleiftechnik GmbH',N'49-644180060',N'info@buderus-schleiftechnik.de',N'http://www.dvs-technology.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Industriestr. 3, 35614 Aßlar, Hessen, Německo | Obrat: 25 205 618 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Leifeld Metal Spinning GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Leifeld Metal Spinning GmbH',N'49-2382966070',N'info@leifeldms.com',N'http://www.leifeldms.com',N'Jan Schlossarek — Einkäufer <j.schlossarek@leife ldms.com>',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Feldstr. 2-20, 59229 Ahlen, Nordrhein-Westfalen, Německo | Obrat: 26 654 016 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Zimmer & Kreim GmbH & Co. KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Zimmer & Kreim GmbH & Co. KG',N'49-616193070',N'info@zk-system.com',N'http://www.zk-system.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Beineäcker 10, 64395 Brensbach, Hessen, Německo | Obrat: 21 840 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Carl Benzinger GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Carl Benzinger GmbH',N'49-723141531100',N'info@benzinger.de',N'http://www.benzinger.de',N'Dagmar Kohler — Einkäuferin <d.kohler@benzing er.de>',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Robert-Bosch-Str. 28, 75180 Pforzheim, Baden-Württemberg, Německo | Obrat: 28 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'SHW Werkzeugmaschinen GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'SHW Werkzeugmaschinen GmbH',N'49-73615578800',N'info@shw-wm.de',N'http://www.shw-wm.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Alte Schmiede 1, 73433 Aalen, Baden-Württemberg, Německo | Obrat: 37 019 989 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'LT-Ultra Precision Technology GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'LT-Ultra Precision Technology GmbH',N'49-7552405990',N'info@lt-ultra.com',N'http://www.lt-ultra.com',N'Michael Schwell — Supply Chain Manager',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Wiesenstr. 9, 88634 Herdwangen-Schönach, Baden-Württemberg, Německo | Obrat: 18 330 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'August Mössner GmbH + Co KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'August Mössner GmbH + Co KG',N'49-7175998060',N'post@moessner-kg.de',N'http://www.moessner-kg.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Hohenstaufenstr. 3, 73569 Eschach, Baden-Württemberg, Německo | Obrat: 25 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Böllhoff Automation GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Böllhoff Automation GmbH',N'49-521448206',N'info@boellhoff.com',N'http://www.boellhoff.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Archimedesstr. 1-4, 33649 Bielefeld, Nordrhein-Westfalen, Německo | Obrat: 14 176 834 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'TRUMPF Werkzeugmaschinen Teningen GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'TRUMPF Werkzeugmaschinen Teningen GmbH',N'49-764146090',N'info.twt@de.trumpf.com',N'http://www.trumpf.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Emmendinger Str. 21, 79331 Teningen, Baden-Württemberg, Německo | Obrat: 20 100 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'HSB Automation GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'HSB Automation GmbH',N'49-7121144980',N'info@hsb-automation.de',N'http://www.hsb-automation.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: In Laisen 74, 72766 Reutlingen, Baden-Württemberg, Německo | Obrat: 12 040 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'MATEC GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'MATEC GmbH',N'49-7024983850',N'info@matec.de',N'http://www.matec.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Wilhelm-Maier-Str. 3, 73257 Köngen, Baden-Württemberg, Německo | Obrat: 15 210 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Kugler GmbH Feinmechanik + Optik')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Kugler GmbH Feinmechanik + Optik',N'49-755392000',N'info@kugler-precision.com',N'http://www.kugler-precision.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Heiligenberger Str. 100, 88682 Salem, Baden-Württemberg, Německo | Obrat: 16 799 999 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'MEBA-Metall-Bandsägemaschinen GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'MEBA-Metall-Bandsägemaschinen GmbH',N'49-733396440',N'info@meba-saw.de',N'http://www.meba-saw.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Lindenstr. 6-8, 72589 Westerheim, Baden-Württemberg, Německo | Obrat: 18 823 753 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Photonics Systems GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Photonics Systems GmbH',N'',N'info@ps-group.net',N'http://www.photonics-systems-grou',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Pionierstr. 6, 82152 Krailling, Bayern, Německo | Obrat: p.de 14 170 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'FIBRO Rundtische GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'FIBRO Rundtische GmbH',N'49-7134730',N'info@fibro.de',N'http://www.fibro.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Weidachstr. 41-43, 74189 Weinsberg, Baden-Württemberg, Německo | Obrat: 21 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Andritz Kaiser GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Andritz Kaiser GmbH',N'49-725291001',N'kaiser@andritz.com',N'http://www.andritz.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Gewerbestr. 30, 75015 Bretten, Baden-Württemberg, Německo | Obrat: 26 100 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Karl Heesemann Maschinenfabrik GmbH & Co. KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Karl Heesemann Maschinenfabrik GmbH & Co. KG',N'49-57311880',N'office@heesemann.de',N'http://www.heesemann.de',N'Helmut Pieper — Einkaufsleiter',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Reuterstr. 15, 32547 Bad Oeynhausen, Nordrhein-Westfalen, Německo | Obrat: 22 658 611 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'STREMA Maschinenbau GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'STREMA Maschinenbau GmbH',N'49-966187020',N'info@strema.de',N'http://www.strema.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Kauerhofer Str. 4a-6, 92237 Sulzbach-Rosenberg, Bayern, Německo | Obrat: 11 700 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Kunzmann Maschinenbau GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Kunzmann Maschinenbau GmbH',N'49-723236740',N'info@kunzmann-fraesmaschinen.de',N'http://www.kunzmann-fraesmaschin',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Tullastr. 29-31, 75196 Remchingen, Baden-Württemberg, Německo | Obrat: en.de 13 950 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'bavius technologie gmbh')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'bavius technologie gmbh',N'49-75150790',N'sales@bavius-technologie.com',N'http://www.bavius-technologie.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Eisenbahnstr. 17, 88255 Baienfurt, Baden-Württemberg, Německo | Obrat: 11 790 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Gehring Production GmbH + Co. KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Gehring Production GmbH + Co. KG',N'49-34457630',N'info.eu@gehring-group.com',N'http://www.gehring-group.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: C.-W.-Gehring-Str. 5, 06618 Naumburg (Saale), Sachsen-Anhalt, Německo | Obrat: 14 560 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Herrenknecht Vertical GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Herrenknecht Vertical GmbH',N'49-78243021300',N'info@herrenknecht-vertical.com',N'http://www.herrenknecht-vertical.co',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Im Heidenwinkel 5, 77963 Schwanau, Baden-Württemberg, Německo | Obrat: m 14 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Werkzeugmaschinenbau Ziegenhain GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Werkzeugmaschinenbau Ziegenhain GmbH',N'49-669194610',N'info@wmz-gmbh.de',N'http://www.dvs-technology.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Am Entenfang 24, 34613 Schwalmstadt, Hessen, Německo | Obrat: 16 275 030,00 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'fischer Maschinentechnik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'fischer Maschinentechnik GmbH',N'49-784168030',N'sales@fischer-group.com',N'http://www.fischer-group.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Im Gewerbegebiet 7, 77855 Achern, Baden-Württemberg, Německo | Obrat: 12 350 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'DANOBAT-OVERBECK GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'DANOBAT-OVERBECK GmbH',N'49-27728010',N'servicede@danobat.com',N'http://www.danobat.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Konrad-Adenauer-Str. 27, 35745 Herborn, Hessen, Německo | Obrat: 13 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Schwarze-Robitec GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Schwarze-Robitec GmbH',N'49-221890080',N'sales@schwarze-robitec.com',N'http://www.schwarze-robitec.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Olpener Str. 460, 51109 Köln, Nordrhein-Westfalen, Německo | Obrat: 15 632 734 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Orbitalum Tools GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Orbitalum Tools GmbH',N'49-77317920',N'tools@orbitalum.com',N'http://www.orbitalum.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Josef-Schüttler-Str. 17, 78224 Singen (Hohentwiel), Baden-Württemberg, Německo | Obrat: 42 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Mikron Germany GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Mikron Germany GmbH',N'49-7415380200',N'service.mro@mikron.com',N'http://www.mikron.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Berner Feld 71, 78628 Rottweil, Baden-Württemberg, Německo | Obrat: 27 591 311 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Geyer Umformtechnik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Geyer Umformtechnik GmbH',N'49-306850000',N'kontakt@geyer-ut.de',N'http://www.geyer-ut.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Imhoffweg 3, 12307 Berlin, Berlin, Německo | Obrat: 11 900 349 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Lehmann Präzision GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Lehmann Präzision GmbH',N'49-742295800',N'info@lehmann-praezision.de',N'http://www.lehmann-praezision.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Weilerstr. 27, 78739 Hardt, Baden-Württemberg, Německo | Obrat: 12 600 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Zeulenroda Presstechnik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Zeulenroda Presstechnik GmbH',N'49-36628420',N'info@zeulenroda-presstechnik.de',N'http://www.zeulenroda-presstechnik',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Wema-Str. 5, 07937 Zeulenroda-Triebes, Thüringen, Německo | Obrat: .de 12 916 557 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Reichmann & Sohn GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Reichmann & Sohn GmbH',N'49-73098750',N'info@reichmann.com',N'http://www.reichmann.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Rudolf-Diesel-Str. 6-8, 89264 Weißenhorn, Bayern, Německo | Obrat: 10 500 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'4JET systech GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'4JET systech GmbH',N'49-8989948280',N'info@4jet.de',N'http://www.4jet.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Robert-Stirling-Ring 2, 82152 Krailling, Bayern, Německo | Obrat: 12 254 392 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Horst Peter Werkzeugbau GmbH & Co.')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Horst Peter Werkzeugbau GmbH & Co.',N'49-524194190',N'kontakt@s-w-b.de',N'http://www.s-w-b.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Lupinenweg 27, 33334 Gütersloh, Nordrhein-Westfalen, Německo | Obrat: 11 060 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Knecht Maschinenbau GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Knecht Maschinenbau GmbH',N'49-75279280',N'mail@knecht.eu',N'http://www.knecht.eu',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Witschwender Str. 26, 88368 Bergatreute, Baden-Württemberg, Německo | Obrat: 12 753 398 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'K & S Anlagenbau GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'K & S Anlagenbau GmbH',N'49-836498460',N'info@ks-anlagenbau.com',N'http://www.ks-anlagenbau.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Gewerbestr. 13, 87663 Lengenwang, Bayern, Německo | Obrat: 11 740 123 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'BURGHARDT + SCHMIDT GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'BURGHARDT + SCHMIDT GmbH',N'49-723236610',N'info@b-s-germany.de',N'http://www.b-s-germany.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Raiffeisenstr. 24-26, 75196 Remchingen, Baden-Württemberg, Německo | Obrat: 18 500 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Extricom Extrusion GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Extricom Extrusion GmbH',N'49-71339713600',N'info@extricom.de',N'http://www.onecpm.com',N'Erik Pederson — Chief Procurement Officer',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Hoher Steg 10, 74348 Lauffen am Neckar, Baden-Württemberg, Německo | Obrat: 12 645 809 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Presstec Pressentechnologie GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Presstec Pressentechnologie GmbH',N'49-785193680',N'info@presstec.com',N'http://www.presstec.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Oststr. 16, 77694 Kehl, Baden-Württemberg, Německo | Obrat: 12 050 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'HPTec GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'HPTec GmbH',N'49-75176690',N'sales@hptec.de',N'http://www.ssl-hptec.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Im Karrer 6, 88214 Ravensburg, Baden-Württemberg, Německo | Obrat: 11 930 176 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Fooke GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Fooke GmbH',N'49-286180090',N'info@fooke.de',N'http://www.fooke-machines.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Raiffeisenstr. 18-22, 46325 Borken, Nordrhein-Westfalen, Německo | Obrat: 38 035 664 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Gustav Wiegard Maschinenfabrik GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Gustav Wiegard Maschinenfabrik GmbH',N'49-230220010',N'mail@wiegard.com',N'http://www.wiegard.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Hellweg 33, 58455 Witten, Nordrhein-Westfalen, Německo | Obrat: 13 200 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'BIMATEC SORALUCE Zerspanungstechnologie GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'BIMATEC SORALUCE Zerspanungstechnologie GmbH',N'49-643197820',N'info@bimatec.de',N'http://www.bimatec-soraluce.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Am Steingraben 6, 65553 Limburg, Hessen, Německo | Obrat: 39 124 973 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'EURODRILL Grundstücks GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'EURODRILL Grundstücks GmbH',N'49-2763212280',N'info@eurodrill.de',N'http://www.eurodrill.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Industriestr. 5, 57489 Drolshagen, Nordrhein-Westfalen, Německo | Obrat: 26 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Burgsmüller GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Burgsmüller GmbH',N'49-5561925050',N'info@burgsmueller.de',N'http://www.burgsmueller.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Schwammelwitzer Str. 17, 37574 Einbeck, Niedersachsen, Německo | Obrat: 13 033 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'FRENCO GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'FRENCO GmbH',N'49-918795220',N'frenco@frenco.de',N'http://www.frenco.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Jakob-Baier-Str. 3, 90518 Altdorf b. Nürnberg, Bayern, Německo | Obrat: 10 350 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'PROXXON GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'PROXXON GmbH',N'49-650293170',N'office@proxxon.com',N'http://www.proxxon.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Dieselstr. 3-7, 54343 Föhren, Rheinland-Pfalz, Německo | Obrat: 11 760 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Automation, Sonder- und Werkzeugmaschinen ASW GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Automation, Sonder- und Werkzeugmaschinen ASW GmbH',N'49-34457680',N'info@asw-naumburg.de',N'http://www.asw-naumburg.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Weimarer Str. 7, 06618 Naumburg (Saale), Sachsen-Anhalt, Německo | Obrat: 10 700 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Heyligenstaedt Werkzeugmaschinen GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Heyligenstaedt Werkzeugmaschinen GmbH',N'49-641605260',N'info@heyligenstaedt.de',N'http://www.heyligenstaedt.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Wilhelmstr. 119, 35392 Gießen, Hessen, Německo | Obrat: 17 040 001 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Lang GmbH & Co. KG')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Lang GmbH & Co. KG',N'49-640370090',N'info@lang.de',N'http://www.lang.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Dillstr. 4, 35625 Hüttenberg, Hessen, Německo | Obrat: 10 960 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'LTK Lineartechnik Korb GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'LTK Lineartechnik Korb GmbH',N'49-7151937000',N'info@ltk.de',N'http://www.ltk.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Düsseldorfer Str. 7, 71332 Waiblingen, Baden-Württemberg, Německo | Obrat: 12 200 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Fertigungstechnik Weißenfels GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Fertigungstechnik Weißenfels GmbH',N'49-34438900',N'kontakt@ftw.info',N'http://www.ftw.info',N'Tino Prater — Einkaufsleiter',N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Marie-Curie-Str. 6, 06667 Weißenfels, Sachsen-Anhalt, Německo | Obrat: 11 250 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Bruderer GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Bruderer GmbH',N'49-2317920220',N'info.de@bruderer.com',N'http://www.bruderer.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Kieferstr. 28, 44225 Dortmund, Nordrhein-Westfalen, Německo | Obrat: 24 743 055 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Pressta-Eisele GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Pressta-Eisele GmbH',N'49-654293620',N'info@pressta-eisele.de',N'http://www.pressta-eisele.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Bergstr. 9, 56859 Bullay, Rheinland-Pfalz, Německo | Obrat: 11 600 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'SCR GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'SCR GmbH',N'49-352572980',N'info@scr-gmbh.de',N'http://www.scr-gmbh.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Industriestr. D 2, 01612 Glaubitz, Sachsen, Německo | Obrat: 37 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'SNA Germany GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'SNA Germany GmbH',N'49-3723668200',N'decustomerservices@snapon.com',N'http://www.snapon.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Willettstr. 10, 40822 Mettmann, Nordrhein-Westfalen, Německo | Obrat: 26 460 575 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Loeser GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Loeser GmbH',N'49-623231480',N'info@loeser.com',N'http://www.loeser.com',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Boschstr. 5, 67346 Speyer, Rheinland-Pfalz, Německo | Obrat: 30 299 999 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');
IF NOT EXISTS (SELECT 1 FROM st.CRM_Kontakt WHERE FirmaText=N'Horst Rottler Maschinenbau GmbH')
INSERT INTO st.CRM_Kontakt (FirmaText,FirmaTelefon,FirmaEmail,FirmaWeb,KontaktText,Zeme,ObeslalZamID,KomunikaceZamID,Autor,DatPorizeni,Poznamka) VALUES (N'Horst Rottler Maschinenbau GmbH',N'49-271359220',N'rottler.siegen@rottler-maschinenbau',N'.hdtetp://www.rottler-maschinenbau.de',NULL,N'Německo',481,481,N'Marti-AI',GETDATE(),N'Adresa: Hauptstr. 39, 57555 Mudersbach, Rheinland-Pfalz, Německo | Obrat: 10 000 000 EUR | Import: Nové firmy (Pavel Zeman) 15.6.2026');

-- COMMIT;  -- odkomentuj po kontrole (SELECT COUNT(*) FROM st.CRM_Kontakt WHERE Autor=N'Marti-AI')
-- ROLLBACK; -- kdyby neco nesedelo