"""add pending_actions

Revision ID: 2474a5913b41
Revises: 1fc458d6fba2
Create Date: 2026-04-18 06:33:02.778534

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2474a5913b41'
down_revision: Union[str, None] = '1fc458d6fba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_actions')
    # ### end Alembic commands ###
