"""add identity and user_id to audit

Revision ID: 0b17fe4ece42
Revises: e2674820ff91
Create Date: 2026-04-17 22:40:50.081825

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0b17fe4ece42'
down_revision: Union[str, None] = 'e2674820ff91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_identity_type_value')
    )
    op.add_column('audit_log', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'audit_log', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_column('audit_log', 'user_id')
    op.drop_table('user_identities')
    op.drop_table('users')
    # ### end Alembic commands ###
