# -*- coding: utf-8 -*-
"""Katalog 93 kontrol ISO 27001:2022 Annex A — seed pro tenant SoA (iso_control)."""
# (kod, oblast, nazev, apl_bool, stav, zduvodneni, dukaz)
CONTROLS = [
    ("A.5.1", "A.5 Organizační", "Politiky bezpečnosti informací", True, "ROZPRACOVÁNO", "Politika IS (DOC-02) + politiky DOC-09..15", "DOC-02; DOC-09..15"),
    ("A.5.2", "A.5 Organizační", "Role a odpovědnosti", True, "HOTOVO", "Definováno v DOC-03", "DOC-03"),
    ("A.5.3", "A.5 Organizační", "Oddělení neslučitelných povinností", True, "ROZPRACOVÁNO", "Kompenzováno schvalováním se stopou", "3-actor PG path; fw.claude_write_request"),
    ("A.5.4", "A.5 Organizační", "Odpovědnosti vedení", True, "ROZPRACOVÁNO", "Vedení vyhlašuje politiku a dává zdroje", "DOC-02"),
    ("A.5.5", "A.5 Organizační", "Kontakt s úřady", True, "ZBÝVÁ", "Kontakty ÚOOÚ/NÚKIB/Policie/datovky", "—"),
    ("A.5.6", "A.5 Organizační", "Kontakt se zájmovými skupinami", True, "PROCES-ISMS", "Sledování zdrojů o bezpečnosti", "—"),
    ("A.5.7", "A.5 Organizační", "Zpravodajství o hrozbách", True, "ROZPRACOVÁNO", "Sledování zranitelností a hrozeb", "scanner filtr v middleware"),
    ("A.5.8", "A.5 Organizační", "Bezpečnost v projektovém řízení", True, "HOTOVO", "Security by design (DOC-14)", "informed-consent design proces"),
    ("A.5.9", "A.5 Organizační", "Evidence aktiv", True, "ROZPRACOVÁNO", "Evidence a klasifikace (DOC-15)", "DOC-15 + tenant.mig_item (654 obj.)"),
    ("A.5.10", "A.5 Organizační", "Akceptovatelné použití aktiv", True, "ROZPRACOVÁNO", "Pravidla (DOC-13)", "DOC-13"),
    ("A.5.11", "A.5 Organizační", "Vrácení aktiv", True, "EUROSOFT-INFRA", "Proces offboardingu (DOC-13)", "—"),
    ("A.5.12", "A.5 Organizační", "Klasifikace informací", True, "ROZPRACOVÁNO", "Klasifikační schéma (DOC-15)", "privacy tiers (vault/self/HR/confidential)"),
    ("A.5.13", "A.5 Organizační", "Označování informací", True, "ROZPRACOVÁNO", "Dokumenty nesou klasifikaci", "klasifikace 'Interní' na docs"),
    ("A.5.14", "A.5 Organizační", "Přenos informací", True, "HOTOVO", "Šifrovaný přenos (HTTPS/TLS)", "HTTPS; MCP šifr. kanál; single SIM; ISDS"),
    ("A.5.15", "A.5 Organizační", "Řízení přístupu", True, "HOTOVO", "Role a ACL, nejnižší oprávnění (DOC-09)", "RBAC role; tenant.dir_access_log"),
    ("A.5.16", "A.5 Organizační", "Správa identit", True, "HOTOVO", "Jednoznačné identity, životní cyklus", "users/persona/login_name"),
    ("A.5.17", "A.5 Organizační", "Autentizační informace", True, "ROZPRACOVÁNO", "MFA (magic-link/SMS) + šifr. trezor", "vault Fernet; fw.phone_verify; fw.user_pin; AppEnvironmentExtra"),
    ("A.5.18", "A.5 Organizační", "Přístupová práva", True, "ROZPRACOVÁNO", "Přidělování/odebírání, přezkum (DOC-09)", "role model; fw.impersonation_log"),
    ("A.5.19", "A.5 Organizační", "Bezpečnost ve vztazích s dodavateli", True, "ROZPRACOVÁNO", "Politika dodavatelů (DOC-12)", "DOC-12"),
    ("A.5.20", "A.5 Organizační", "Bezpečnost ve smlouvách s dodavateli", True, "ZBÝVÁ", "Bezpečnostní požadavky ve smlouvách", "—"),
    ("A.5.21", "A.5 Organizační", "Bezpečnost v dodavatelském řetězci ICT", True, "ROZPRACOVÁNO", "Posouzení klíčových služeb (DOC-12)", "poetry/npm závislosti"),
    ("A.5.22", "A.5 Organizační", "Monitorování a změny služeb dodavatelů", True, "PROCES-ISMS", "Sledování služeb a změn (DOC-12)", "—"),
    ("A.5.23", "A.5 Organizační", "Bezpečnost při využití cloudu", True, "ROZPRACOVÁNO", "Cloud ČMIS (Praha, ČR)", "cloud APP/SQL + HTTPS"),
    ("A.5.24", "A.5 Organizační", "Plánování řízení incidentů", True, "ROZPRACOVÁNO", "Postup (DOC-10)", "DOC-10"),
    ("A.5.25", "A.5 Organizační", "Posouzení a rozhodnutí o událostech", True, "ROZPRACOVÁNO", "Klasifikace událostí (DOC-10)", "diag_log + anomaly scan"),
    ("A.5.26", "A.5 Organizační", "Reakce na incidenty", True, "ROZPRACOVÁNO", "Definovaný postup (DOC-10)", "DOC-10"),
    ("A.5.27", "A.5 Organizační", "Poučení z incidentů", True, "HOTOVO", "Záznam a poučení (DOC-10, DOC-18)", "gotchas KB + dodatky CLAUDE.md"),
    ("A.5.28", "A.5 Organizační", "Sběr důkazů", True, "HOTOVO", "Neměnný audit log pro forenzní účely", "22 audit tabulek (fw.*/tenant.*)"),
    ("A.5.29", "A.5 Organizační", "Bezpečnost během narušení", True, "ROZPRACOVÁNO", "Plán kontinuity (DOC-11)", "blue-green + fallback (otestováno)"),
    ("A.5.30", "A.5 Organizační", "Připravenost ICT na kontinuitu", True, "ROZPRACOVÁNO", "Zálohy + vysoká dostupnost (DOC-11)", "blue-green"),
    ("A.5.31", "A.5 Organizační", "Právní a smluvní požadavky", True, "ROZPRACOVÁNO", "Evidence požadavků (GDPR, ZP)", "—"),
    ("A.5.32", "A.5 Organizační", "Práva duševního vlastnictví", True, "PROCES-ISMS", "Licence ke kódu a knihovnám", "—"),
    ("A.5.33", "A.5 Organizační", "Ochrana záznamů", True, "HOTOVO", "Ochrana a retence záznamů", "append-only audit log"),
    ("A.5.34", "A.5 Organizační", "Soukromí a ochrana osobních údajů", True, "ROZPRACOVÁNO", "Soulad s GDPR", "consent model; tiers; access logy"),
    ("A.5.35", "A.5 Organizační", "Nezávislé přezkoumání bezpečnosti", True, "ZBÝVÁ", "Interní audit (DOC-16) + certifikace", "DOC-16 program"),
    ("A.5.36", "A.5 Organizační", "Soulad s politikami a normami", True, "ROZPRACOVÁNO", "Kontrola dodržování (DOC-16)", "—"),
    ("A.5.37", "A.5 Organizační", "Dokumentované provozní postupy", True, "HOTOVO", "Provozní postupy (deploy, zálohy, ops)", "CLAUDE.md + docs + deploy postupy"),
    ("A.6.1", "A.6 Lidé", "Prověřování (screening)", True, "EUROSOFT-INFRA", "Ověření při nástupu", "—"),
    ("A.6.2", "A.6 Lidé", "Podmínky pracovního poměru", True, "EUROSOFT-INFRA", "Bezpečnostní povinnosti ve smlouvách", "DOC-13"),
    ("A.6.3", "A.6 Lidé", "Povědomí, vzdělávání a školení", True, "ZBÝVÁ", "Pravidelné poučení (cíl v DOC-08)", "—"),
    ("A.6.4", "A.6 Lidé", "Disciplinární proces", True, "EUROSOFT-INFRA", "Postih dle DOC-02 a ZP", "—"),
    ("A.6.5", "A.6 Lidé", "Odpovědnosti po ukončení", True, "ROZPRACOVÁNO", "Offboarding, mlčenlivost (DOC-13)", "disable/archived + samoopravný roster"),
    ("A.6.6", "A.6 Lidé", "Dohody o mlčenlivosti (NDA)", True, "ROZPRACOVÁNO", "NDA EUROSOFT + vlastní NDA STRATEGIE", "NDA vzor (Zbyněk)"),
    ("A.6.7", "A.6 Lidé", "Práce na dálku", True, "ROZPRACOVÁNO", "Pravidla HO a vzdál. přístupu (DOC-13)", "Phase 38, VPN, trusted devices"),
    ("A.6.8", "A.6 Lidé", "Hlášení bezpečnostních událostí", True, "ROZPRACOVÁNO", "Každý hlásí bez obav (DOC-10)", "diag_log popup alert"),
    ("A.7.1", "A.7 Fyzická", "Fyzické bezpečnostní perimetry", True, "EUROSOFT-INFRA", "Kancelář + servery v DC ČMIS", "—"),
    ("A.7.2", "A.7 Fyzická", "Fyzický vstup", True, "EUROSOFT-INFRA", "Řízený vstup; DC poskytovatele", "—"),
    ("A.7.3", "A.7 Fyzická", "Zabezpečení kanceláří a prostor", True, "EUROSOFT-INFRA", "Zamykání, zabezpečení pracoviště", "—"),
    ("A.7.4", "A.7 Fyzická", "Fyzické monitorování", True, "EUROSOFT-INFRA", "Zajišťuje DC ČMIS", "—"),
    ("A.7.5", "A.7 Fyzická", "Ochrana před fyzickými hrozbami", True, "EUROSOFT-INFRA", "DC (požár, napájení)", "—"),
    ("A.7.6", "A.7 Fyzická", "Práce v zabezpečených oblastech", True, "EUROSOFT-INFRA", "Relevantní pro DC", "—"),
    ("A.7.7", "A.7 Fyzická", "Čistý stůl a obrazovka", True, "PROCES-ISMS", "Pravidlo čistého stolu (DOC-13)", "DOC-13"),
    ("A.7.8", "A.7 Fyzická", "Umístění a ochrana zařízení", True, "EUROSOFT-INFRA", "Stanice chráněny; servery v DC", "—"),
    ("A.7.9", "A.7 Fyzická", "Bezpečnost aktiv mimo prostory", True, "ROZPRACOVÁNO", "Na stanicích nejsou zák. data; ESET", "ESET"),
    ("A.7.10", "A.7 Fyzická", "Nosiče dat", True, "ROZPRACOVÁNO", "Řízení a bezpečná likvidace", "—"),
    ("A.7.11", "A.7 Fyzická", "Podpůrné technické vybavení", True, "EUROSOFT-INFRA", "Napájení/chlazení DC ČMIS", "—"),
    ("A.7.12", "A.7 Fyzická", "Bezpečnost kabeláže", True, "EUROSOFT-INFRA", "V kompetenci DC", "—"),
    ("A.7.13", "A.7 Fyzická", "Údržba zařízení", True, "EUROSOFT-INFRA", "Údržba stanic a serverů", "—"),
    ("A.7.14", "A.7 Fyzická", "Bezpečná likvidace / opětovné použití", True, "ROZPRACOVÁNO", "Vymazání dat před vyřazením", "—"),
    ("A.8.1", "A.8 Technologická", "Koncová zařízení uživatelů", True, "ROZPRACOVÁNO", "ESET; na stanicích nejsou zák. data", "trusted devices; ESET"),
    ("A.8.2", "A.8 Technologická", "Privilegovaná přístupová práva", True, "ROZPRACOVÁNO", "Oddělené role, nejnižší oprávnění", "3-actor PG; ops whitelist; approval banner; fw.impersonation_log"),
    ("A.8.3", "A.8 Technologická", "Omezení přístupu k informacím", True, "HOTOVO", "Tenant a role omezují přístup (ACL)", "persona scope ACL; access logy"),
    ("A.8.4", "A.8 Technologická", "Přístup ke zdrojovému kódu", True, "ROZPRACOVÁNO", "Git s řízeným přístupem (PAT)", "privátní git; PAT; per-instance author"),
    ("A.8.5", "A.8 Technologická", "Bezpečná autentizace", True, "HOTOVO", "MFA (magic-link / SMS)", "Phase 38 + PIN/SMS 2FA"),
    ("A.8.6", "A.8 Technologická", "Řízení kapacity", True, "ROZPRACOVÁNO", "Sledování kapacity serverů a DB", "cost dashboard; llm_calls"),
    ("A.8.7", "A.8 Technologická", "Ochrana před malwarem", True, "EUROSOFT-INFRA", "Antivir ESET (EUROSOFT-System)", "ESET"),
    ("A.8.8", "A.8 Technologická", "Správa technických zranitelností", True, "ZBÝVÁ", "Aktualizace OS a knihoven", "—"),
    ("A.8.9", "A.8 Technologická", "Správa konfigurací", True, "HOTOVO", "Konfigurace verzována; deploy se stopou", "git single source; API versioning"),
    ("A.8.10", "A.8 Technologická", "Mazání informací", True, "ROZPRACOVÁNO", "Soft delete + řízené mazání dle retence", "request_forget; anonymizace"),
    ("A.8.11", "A.8 Technologická", "Maskování dat", True, "ROZPRACOVÁNO", "Citlivá pole v UI jako '[omezeno]'", "UPN maskování; [omezeno]"),
    ("A.8.12", "A.8 Technologická", "Prevence úniku dat", True, "ROZPRACOVÁNO", "Řízené kanály, šifrování", "secrets nikdy v logu; persona izolace"),
    ("A.8.13", "A.8 Technologická", "Zálohování informací", True, "ROZPRACOVÁNO", "Denní zálohy (03:00); offsite v zavádění", "denní zálohy ČMIS"),
    ("A.8.14", "A.8 Technologická", "Redundance zpracování", True, "HOTOVO", "Vysoká dostupnost (blue-green)", "blue-green + cloud mirror (otestováno)"),
    ("A.8.15", "A.8 Technologická", "Protokolování (logging)", True, "HOTOVO", "Neměnný append-only audit log", "fw.diag_log"),
    ("A.8.16", "A.8 Technologická", "Monitorování činností", True, "ROZPRACOVÁNO", "Sledování provozu a událostí", "anomaly scan; diag_log"),
    ("A.8.17", "A.8 Technologická", "Synchronizace času", True, "HOTOVO", "Synchronizace času serverů (NTP)", "NTP + Europe/Prague"),
    ("A.8.18", "A.8 Technologická", "Privilegované systémové nástroje", True, "ROZPRACOVÁNO", "Omezené a auditované ops (whitelist)", "ops framework; bridge; fw.ops_request"),
    ("A.8.19", "A.8 Technologická", "Instalace softwaru na provozní systémy", True, "HOTOVO", "Řízený deploy přes schválený proces", "AUTO-DEPLOY + py_compile gate + advisory lock"),
    ("A.8.20", "A.8 Technologická", "Bezpečnost sítí", True, "ROZPRACOVÁNO", "TLS, oddělení produkce, reverzní proxy", "Mikrotik whitelist; Caddy; HTTPS"),
    ("A.8.21", "A.8 Technologická", "Bezpečnost síťových služeb", True, "ROZPRACOVÁNO", "Zabezpečené služby a rozhraní", "IP whitelist; single SIM"),
    ("A.8.22", "A.8 Technologická", "Segregace sítí", True, "ROZPRACOVÁNO", "Oddělení produkce a interního prostředí", "on-prem↔cloud přes whitelist IP"),
    ("A.8.23", "A.8 Technologická", "Filtrování webu", True, "ROZPRACOVÁNO", "Omezeně; rozsah koncových stanic", "scanner filtr"),
    ("A.8.24", "A.8 Technologická", "Použití kryptografie", True, "ROZPRACOVÁNO", "Šifrování přenosu (TLS) i tajemství", "HTTPS + Fernet vault"),
    ("A.8.25", "A.8 Technologická", "Bezpečný životní cyklus vývoje", True, "ROZPRACOVÁNO", "Bezpečný vývoj (DOC-14)", "git; blue-green; py_compile gate"),
    ("A.8.26", "A.8 Technologická", "Bezpečnostní požadavky aplikací", True, "ROZPRACOVÁNO", "Bezpečnost součástí požadavků", "defense-in-depth doctrine"),
    ("A.8.27", "A.8 Technologická", "Bezpečná architektura a principy", True, "HOTOVO", "Security by design, vícevrstvá ochrana", "vrstvený kontext; defense in depth"),
    ("A.8.28", "A.8 Technologická", "Bezpečné kódování", True, "ROZPRACOVÁNO", "Zásady bezpečného kódování (DOC-14)", "gotchas KB; Claude review"),
    ("A.8.29", "A.8 Technologická", "Bezpečnostní testování", True, "ROZPRACOVÁNO", "Testování před nasazením", "smoke testy"),
    ("A.8.30", "A.8 Technologická", "Vývoj zajišťovaný externě", False, "NEAPLIKOVATELNÉ", "Vývoj probíhá interně; bez outsourcingu", "—"),
    ("A.8.31", "A.8 Technologická", "Oddělení vývoje, testu a produkce", True, "HOTOVO", "Oddělená produkce a test", "NB dev / cloud prod / blue-green / test DB"),
    ("A.8.32", "A.8 Technologická", "Řízení změn", True, "HOTOVO", "Schvalovací proces změn se stopou", "git + versioning + blue-green + fallback"),
    ("A.8.33", "A.8 Technologická", "Testovací informace", True, "ROZPRACOVÁNO", "Demo data oddělena (demo tenant)", "demo tenant; bez reálných osob"),
    ("A.8.34", "A.8 Technologická", "Ochrana systémů při auditu", True, "ROZPRACOVÁNO", "Auditní činnosti řízeny", "fw.claude_sql_log; read-only guard"),
]
