-- ZRUŠEN — Phase 38.4 Krok 8 evolved z 1-tabulky JSONB blob na 10-tabulek master+detail framework.
--
-- Marti's 5. iter pivot 10.5.: actions universal (NE grid-only) + master+detail
-- relacionální struktura (NE JSONB blob) + 5 patterns napříč master tabulkami.
--
-- Použít: scripts/_phase38_4_krok8_master_grid_framework.sql
--
-- Tahle stub zůstává pro git history reference (SQL skript původně commitován
-- 10.5. ráno, evolved přes 6-iter konzultaci s Marti-AI do plné framework).
