DELETE FROM tenant.rozvrh_bunka WHERE verze_id=4 AND blok='predmet';
INSERT INTO tenant.rozvrh_bunka (verze_id,tenant_id,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok) VALUES
(4,13,3,1,'','4.GD','T9','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(4,13,3,2,'','4.GD','T9','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(4,13,3,4,'','4.GD','XD','','XD','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(4,13,1,3,'','4.GD','XE','','XE','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(4,13,1,6,'','4.GD','T9','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,2,1,'','4.GD','T9','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,4,1,'','4.GD','T9','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,5,4,'','4.GD','XD','','XD','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(4,13,5,5,'','4.GD','XD','','XD','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(4,13,5,1,'','4.GD','XD','','XD','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(4,13,3,5,'','4.GD','XE','','XE','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(4,13,3,6,'','4.GD','XE','','XE','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(4,13,5,6,'','4.GD','XE','','XE','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(4,13,4,9,'','4.GD','T9','','','','Ekonomika a management','UNS6O','','','','',NULL,'predmet'),
(4,13,2,9,'','4.GD','T9','','','','Ekonomika a management','UNS6O','','','','',NULL,'predmet'),
(4,13,3,8,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BŠ','BŠ','',NULL,'predmet'),
(4,13,3,9,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BŠ','BŠ','',NULL,'predmet'),
(4,13,3,10,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BŠ','BŠ','',NULL,'predmet'),
(4,13,1,8,'','4.GD','D4','','D4','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,1,9,'','4.GD','D4','','D4','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,1,10,'','4.GD','D4','','D4','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,3,5,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,3,6,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,3,7,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,3,8,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BNA','BNA','',NULL,'predmet'),
(4,13,3,9,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BNA','BNA','',NULL,'predmet'),
(4,13,3,10,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BNA','BNA','',NULL,'predmet'),
(4,13,3,5,'','4.GD','D6','','D6','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(4,13,3,6,'','4.GD','D6','','D6','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(4,13,3,7,'','4.GD','D6','','D6','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(4,13,3,6,'','4.GD','XD','','XD','','Výtvarná tvorba','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,3,7,'','4.GD','XD','','XD','','Výtvarná tvorba','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,3,9,'','4.GD','XE','','XE','','Výtvarná tvorba','UOS6W','','BK','BK','',NULL,'predmet'),
(4,13,3,10,'','4.GD','XE','','XE','','Výtvarná tvorba','UOS6W','','BK','BK','',NULL,'predmet'),
(4,13,3,8,'','4.GD','XD','','XD','','Motion design','U0SAL','','BPG','BPG','',NULL,'predmet'),
(4,13,3,9,'','4.GD','XD','','XD','','Motion design','U0SAL','','BPG','BPG','',NULL,'predmet'),
(4,13,3,10,'','4.GD','XD','','XD','','Motion design','U0SAL','','BPG','BPG','',NULL,'predmet'),
(4,13,1,8,'','4.GD','XE','','XE','','Motion design','U0SAL','','BNA','BNA','',NULL,'predmet'),
(4,13,1,9,'','4.GD','XE','','XE','','Motion design','U0SAL','','BNA','BNA','',NULL,'predmet'),
(4,13,1,10,'','4.GD','XE','','XE','','Motion design','U0SAL','','BNA','BNA','',NULL,'predmet'),
(4,13,2,8,'','3.GD','5P','','5P','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,2,9,'','3.GD','5P','','5P','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,2,10,'','3.GD','5P','','5P','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,4,8,'','3.GD','5Q','','5Q','','Figurální kresba','UOS6W','','BK','BK','',NULL,'predmet'),
(4,13,4,9,'','3.GD','5Q','','5Q','','Figurální kresba','UOS6W','','BK','BK','',NULL,'predmet'),
(4,13,4,10,'','3.GD','5Q','','5Q','','Figurální kresba','UOS6W','','BK','BK','',NULL,'predmet'),
(4,13,3,1,'','3.GD','0M','','','','Český jazyk a literatura','URS7L','','','','',NULL,'predmet'),
(4,13,3,2,'','3.GD','0M','','','','Český jazyk a literatura','URS7L','','','','',NULL,'predmet'),
(4,13,1,1,'','3.GD','0M','','','','Český jazyk a literatura','URS7L','','','','',NULL,'predmet'),
(4,13,2,1,'','3.GD','5P','','5P','','Počítačová grafika','UXS9D','','IT2','IT2','',NULL,'predmet'),
(4,13,2,2,'','3.GD','5P','','5P','','Počítačová grafika','UXS9D','','IT2','IT2','',NULL,'predmet'),
(4,13,2,3,'','3.GD','5P','','5P','','Počítačová grafika','UXS9D','','IT2','IT2','',NULL,'predmet'),
(4,13,2,6,'','3.GD','5Q','','5Q','','Počítačová grafika','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,2,7,'','3.GD','5Q','','5Q','','Počítačová grafika','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,2,8,'','3.GD','5Q','','5Q','','Počítačová grafika','UXS9D','','BPG','BPG','',NULL,'predmet'),
(4,13,3,5,'','3.GD','0M','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,1,5,'','3.GD','0M','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,4,4,'','3.GD','0M','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,2,5,'','3.GD','5P','','5P','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,2,6,'','3.GD','5P','','5P','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,4,1,'','3.GD','5Q','','5Q','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,4,2,'','3.GD','5Q','','5Q','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,3,8,'','3.GD','5Q','','5Q','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(4,13,3,9,'','3.GD','5Q','','5Q','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(4,13,3,10,'','3.GD','5Q','','5Q','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(4,13,4,1,'','3.GD','5P','','5P','','Motion design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(4,13,4,2,'','3.GD','5P','','5P','','Motion design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(4,13,5,2,'','3.GD','5Q','','5Q','','Motion design','UZSA4','','MM','MM','',NULL,'predmet'),
(4,13,5,3,'','3.GD','5Q','','5Q','','Motion design','UZSA4','','MM','MM','',NULL,'predmet'),
(4,13,5,2,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,5,3,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,4,7,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,4,8,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,4,1,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,4,2,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,2,9,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,2,10,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,2,6,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,2,7,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,4,9,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,4,10,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(4,13,2,5,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,2,6,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,4,9,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,4,10,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,2,9,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,2,10,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,4,7,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,4,8,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,2,7,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,2,8,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,4,1,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,4,2,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(4,13,5,5,'','3.GD','0M','','','','Občanská nauka','UBHJ6','','','','',NULL,'predmet'),
(4,13,1,10,'','3.GD','0M','','','','Občanská nauka','UBHJ6','','','','',NULL,'predmet'),
(4,13,5,1,'','3.GD','5P','','5P','','Písmo','UOS6U','','BD1','BD1','',NULL,'predmet'),
(4,13,5,2,'','3.GD','5P','','5P','','Písmo','UOS6U','','BD1','BD1','',NULL,'predmet'),
(4,13,2,1,'','3.GD','5Q','','5Q','','Písmo','UOS6U','','BD1','BD1','',NULL,'predmet'),
(4,13,2,2,'','3.GD','5Q','','5Q','','Písmo','UOS6U','','BD1','BD1','',NULL,'predmet'),
(4,13,1,8,'','2.GD','BF','','BF','','Výtvarná příprava','UUS8D','','BK','BK','',NULL,'predmet'),
(4,13,1,9,'','2.GD','BF','','BF','','Výtvarná příprava','UUS8D','','BK','BK','',NULL,'predmet'),
(4,13,1,10,'','2.GD','BF','','BF','','Výtvarná příprava','UUS8D','','BK','BK','',NULL,'predmet'),
(4,13,4,10,'','2.GD','7S','','','','Základy ekologie a biologie','U9TI4','','','','',NULL,'predmet'),
(4,13,5,1,'','2.GD','7S','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(4,13,5,2,'','2.GD','7S','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(4,13,1,1,'','2.GD','7S','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(4,13,1,6,'','2.GD','BG','','BG','','Počítačová grafika','UTS88','','BŠ','BŠ','',NULL,'predmet'),
(4,13,1,7,'','2.GD','BG','','BG','','Počítačová grafika','UTS88','','BŠ','BŠ','',NULL,'predmet'),
(4,13,1,8,'','2.GD','BG','','BG','','Počítačová grafika','UTS88','','BŠ','BŠ','',NULL,'predmet'),
(4,13,2,2,'','2.GD','7S','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,3,3,'','2.GD','7S','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,4,3,'','2.GD','7S','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,4,6,'','2.GD','BF','','BF','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,4,7,'','2.GD','BF','','BF','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,5,5,'','2.GD','BG','','BG','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,5,6,'','2.GD','BG','','BG','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,1,6,'','2.GD','BF','','BF','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(4,13,1,7,'','2.GD','BF','','BF','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(4,13,1,9,'','2.GD','BG','','BG','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(4,13,1,10,'','2.GD','BG','','BG','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(4,13,3,10,'','2.GD','7S','','','','Dějiny grafického designu','UPS70','','','','',NULL,'predmet'),
(4,13,3,9,'','2.GD','7S','','','','Občanská nauka','USNKF','','','','',NULL,'predmet'),
(4,13,1,3,'','2.GD','7S','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(4,13,4,1,'','2.GD','7S','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(4,13,2,9,'','2.GD','BF','','BF','','Písmo','UXS9D','','BNA','BNA','',NULL,'predmet'),
(4,13,2,10,'','2.GD','BF','','BF','','Písmo','UXS9D','','BNA','BNA','',NULL,'predmet'),
(4,13,2,9,'','2.GD','BG','','BG','','Písmo','UTS88','','BD1','BD1','',NULL,'predmet'),
(4,13,2,10,'','2.GD','BG','','BG','','Písmo','UTS88','','BD1','BD1','',NULL,'predmet'),
(4,13,2,4,'','1.GD','FW','','FW','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(4,13,2,5,'','1.GD','FW','','FW','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(4,13,2,6,'','1.GD','FW','','FW','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(4,13,3,5,'','1.GD','FX','','FX','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(4,13,3,6,'','1.GD','FX','','FX','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(4,13,3,7,'','1.GD','FX','','FX','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(4,13,3,8,'','1.GD','FW','','FW','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(4,13,3,9,'','1.GD','FW','','FW','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(4,13,3,10,'','1.GD','FW','','FW','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(4,13,1,8,'','1.GD','FX','','FX','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(4,13,1,9,'','1.GD','FX','','FX','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(4,13,1,10,'','1.GD','FX','','FX','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(4,13,5,5,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,5,6,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,5,7,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,1,8,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,1,9,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,1,10,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,2,1,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,2,2,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,2,3,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,2,4,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,2,5,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,2,6,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(4,13,4,5,'','1.GD','FB','','','','Český jazyk a literatura','U0SAM','','','','',NULL,'predmet'),
(4,13,4,6,'','1.GD','FB','','','','Český jazyk a literatura','U0SAM','','','','',NULL,'predmet'),
(4,13,4,2,'','1.GD','FB','','','','Český jazyk a literatura','U0SAM','','','','',NULL,'predmet'),
(4,13,2,2,'','1.GD','FW','','FW','','Počítačová grafika','UNS6G','','BPG','BPG','',NULL,'predmet'),
(4,13,2,3,'','1.GD','FW','','FW','','Počítačová grafika','UNS6G','','BPG','BPG','',NULL,'predmet'),
(4,13,5,6,'','1.GD','FX','','FX','','Počítačová grafika','UNS6G','','BPG','BPG','',NULL,'predmet'),
(4,13,5,7,'','1.GD','FX','','FX','','Počítačová grafika','UNS6G','','BPG','BPG','',NULL,'predmet'),
(4,13,4,8,'','1.GD','FB','','','','Chemie','U2XC7','','','','',NULL,'predmet'),
(4,13,1,1,'','1.GD','FB','','','','Informační a multimediální technologie','UMS61','','IT5','IT5','',NULL,'predmet'),
(4,13,1,2,'','1.GD','FB','','','','Informační a multimediální technologie','UMS61','','IT5','IT5','',NULL,'predmet'),
(4,13,3,1,'','1.GD','FB','','','','Marketingová komunikace','UPS70','','','','',NULL,'predmet'),
(4,13,4,7,'','1.GD','FB','','','','Dějiny umění','UPS70','','51','51','',NULL,'predmet'),
(4,13,3,2,'','1.GD','FB','','','','Fyzika','UZSA3','','','','',NULL,'predmet'),
(4,13,4,9,'','1.GD','FB','','','','Fyzika','UZSA3','','','','',NULL,'predmet'),
(4,13,2,9,'','1.GD','FB','','','','Dějepis','UI7OD','','','','',NULL,'predmet'),
(4,13,4,10,'','1.GD','FB','','','','Dějepis','UI7OD','','','','',NULL,'predmet'),
(4,13,5,3,'','1.GD','FB','','','','Matematika','UZSA3','','','','',NULL,'predmet'),
(4,13,1,4,'','1.GD','FB','','','','Matematika','UZSA3','','','','',NULL,'predmet'),
(4,13,1,7,'','4.MI','XF','','XF','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,1,6,'','4.MI','XG','','XG','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,1,3,'','4.MI','TF','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(4,13,3,2,'','4.MI','TF','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(4,13,5,1,'','4.MI','TF','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(4,13,1,9,'','4.MI','TF','','','','Ekonomika a management','UNS6O','','','','',NULL,'predmet'),
(4,13,3,9,'','4.MI','TF','','','','Ekonomika a management','UNS6O','','','','',NULL,'predmet'),
(4,13,4,9,'','4.MI','XF','','XF','','3D vizualizace','UZS4A','','BŠ','BŠ','',NULL,'predmet'),
(4,13,4,10,'','4.MI','XF','','XF','','3D vizualizace','UZS4A','','BŠ','BŠ','',NULL,'predmet'),
(4,13,2,8,'','4.MI','XF','','XF','','Design nábytku','UVS8S','','D','D','',NULL,'predmet'),
(4,13,2,9,'','4.MI','XF','','XF','','Design nábytku','UVS8S','','D','D','',NULL,'predmet'),
(4,13,2,10,'','4.MI','XF','','XF','','Design nábytku','UVS8S','','D','D','',NULL,'predmet'),
(4,13,2,9,'','4.MI','XG','','XG','','Web design a multimediální aplikace','UMS61','','BŠ','BŠ','',NULL,'predmet'),
(4,13,2,10,'','4.MI','XG','','XG','','Web design a multimediální aplikace','UMS61','','BŠ','BŠ','',NULL,'predmet'),
(4,13,4,8,'','4.MI','EA','','EA','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(4,13,4,9,'','4.MI','EA','','EA','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(4,13,4,10,'','4.MI','EA','','EA','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(4,13,2,8,'','4.MI','EA','','EA','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,2,9,'','4.MI','EA','','EA','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,2,10,'','4.MI','EA','','EA','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,2,1,'','4.MI','TF','','','','Matematika','UZS4V','','','','',NULL,'predmet'),
(4,13,4,1,'','4.MI','TF','','','','Matematika','UZS4V','','','','',NULL,'predmet'),
(4,13,2,8,'','3.MI','5R','','5R','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(4,13,2,9,'','3.MI','5R','','5R','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(4,13,2,10,'','3.MI','5R','','5R','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(4,13,3,3,'','3.MI','5R','','5R','','Technologie','USS80','','IT2','IT2','',NULL,'predmet'),
(4,13,3,4,'','3.MI','5R','','5R','','Technologie','USS80','','IT2','IT2','',NULL,'predmet'),
(4,13,5,7,'','3.MI','0P','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,1,9,'','3.MI','5R','','5R','','Počítačová grafika','UOS6U','','BŠ','BŠ','',NULL,'predmet'),
(4,13,1,10,'','3.MI','5R','','5R','','Počítačová grafika','UOS6U','','BŠ','BŠ','',NULL,'predmet'),
(4,13,4,9,'','3.MI','5S','','5S','','Počítačová grafika','UPS70','','BNA','BNA','',NULL,'predmet'),
(4,13,4,10,'','3.MI','5S','','5S','','Počítačová grafika','UPS70','','BNA','BNA','',NULL,'predmet'),
(4,13,4,5,'','3.MI','0P','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(4,13,5,6,'','3.MI','0P','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(4,13,3,1,'','3.MI','0P','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(4,13,3,8,'','3.MI','5R','','5R','','Konstrukční příprava','UZS4O','','D','D','',NULL,'predmet'),
(4,13,3,9,'','3.MI','5R','','5R','','Konstrukční příprava','UZS4O','','D','D','',NULL,'predmet'),
(4,13,3,10,'','3.MI','5R','','5R','','Konstrukční příprava','UZS4O','','D','D','',NULL,'predmet'),
(4,13,4,8,'','3.MI','5R','','5R','','Design interieru a navrhování','UVS8S','','BD1','BD1','',NULL,'predmet'),
(4,13,4,9,'','3.MI','5R','','5R','','Design interieru a navrhování','UVS8S','','BD1','BD1','',NULL,'predmet'),
(4,13,4,10,'','3.MI','5R','','5R','','Design interieru a navrhování','UVS8S','','BD1','BD1','',NULL,'predmet'),
(4,13,2,8,'','3.MI','5S','','5S','','3D Animace','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,2,9,'','3.MI','5S','','5S','','3D Animace','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,2,10,'','3.MI','5S','','5S','','3D Animace','UUS8F','','MM','MM','',NULL,'predmet'),
(4,13,3,7,'','3.MI','5S','','5S','','Web design a multimediální aplikace','UMS61','','MM','MM','',NULL,'predmet'),
(4,13,3,8,'','3.MI','5S','','5S','','Web design a multimediální aplikace','UMS61','','MM','MM','',NULL,'predmet'),
(4,13,1,3,'','3.MI','5S','','5S','','Web design a multimediální aplikace','UMS61','','IT2','IT2','',NULL,'predmet'),
(4,13,1,8,'','3.MI','KF','','KF','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(4,13,1,9,'','3.MI','KF','','KF','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(4,13,1,10,'','3.MI','KF','','KF','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(4,13,3,8,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','IT2','IT2','',NULL,'predmet'),
(4,13,3,9,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','IT2','IT2','',NULL,'predmet'),
(4,13,3,10,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','IT2','IT2','',NULL,'predmet'),
(4,13,4,8,'','3.MI','KF','','KF','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,4,9,'','3.MI','KF','','KF','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,4,10,'','3.MI','KF','','KF','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,3,3,'','3.MI','KG','','KG','','Fotografie 2','U0SAC','','MM','MM','',NULL,'predmet'),
(4,13,3,4,'','3.MI','KG','','KG','','Fotografie 2','U0SAC','','MM','MM','',NULL,'predmet'),
(4,13,3,5,'','3.MI','KG','','KG','','Fotografie 2','U0SAC','','MM','MM','',NULL,'predmet'),
(4,13,4,1,'','3.MI','0P','','','','Občanská nauka','UZS4A','','','','',NULL,'predmet'),
(4,13,5,1,'','3.MI','0P','','','','Občanská nauka','UZS4A','','','','',NULL,'predmet'),
(4,13,4,3,'','3.MI','0P','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(4,13,2,1,'','3.MI','0P','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(4,13,4,7,'','2.MI','BJ','','BJ','','Technologie','USS80','','IT2','IT2','',NULL,'predmet'),
(4,13,3,2,'','2.MI','7V','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,3,3,'','2.MI','7V','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,4,1,'','2.MI','7V','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,3,9,'','2.MI','BI','','BI','','Počítačová grafika','UMS61','','MM','MM','',NULL,'predmet'),
(4,13,3,10,'','2.MI','BI','','BI','','Počítačová grafika','UMS61','','MM','MM','',NULL,'predmet'),
(4,13,2,9,'','2.MI','BJ','','BJ','','Počítačová grafika','UPS70','','BPG','BPG','',NULL,'predmet'),
(4,13,2,10,'','2.MI','BJ','','BJ','','Počítačová grafika','UPS70','','BPG','BPG','',NULL,'predmet'),
(4,13,4,6,'','2.MI','7V','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,3,6,'','2.MI','7V','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,2,5,'','2.MI','7V','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(4,13,1,7,'','2.MI','BI','','BI','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,1,8,'','2.MI','BI','','BI','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,1,9,'','2.MI','BI','','BI','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,1,8,'','2.MI','BJ','','BJ','','Konstrukční příprava','USS80','','D','D','',NULL,'predmet'),
(4,13,1,9,'','2.MI','BJ','','BJ','','Konstrukční příprava','USS80','','D','D','',NULL,'predmet'),
(4,13,1,10,'','2.MI','BJ','','BJ','','Konstrukční příprava','USS80','','D','D','',NULL,'predmet'),
(4,13,4,5,'','2.MI','BI','','BI','','Scénáristika','UUS8I','','MM','MM','',NULL,'predmet'),
(4,13,1,7,'','2.MI','BJ','','BJ','','Dějiny designu','UZS4A','','','','',NULL,'predmet'),
(4,13,4,3,'','2.MI','BI','','BI','','Dějiny multimedií','UMS61','','','','',NULL,'predmet'),
(4,13,4,9,'','2.MI','BI','','BI','','5F','UUS8F','','','','',NULL,'predmet'),
(4,13,4,10,'','2.MI','BI','','BI','','5F','UUS8F','','','','',NULL,'predmet'),
(4,13,1,10,'','2.MI','BI','','BI','','5F','UUS8F','','','','',NULL,'predmet'),
(4,13,2,9,'','2.MI','BI','','BI','','5G','U0SAJ','','','','',NULL,'predmet'),
(4,13,2,10,'','2.MI','BI','','BI','','5G','U0SAJ','','','','',NULL,'predmet'),
(4,13,1,3,'','2.MI','7V','','','','Občanská nauka','USNKF','','','','',NULL,'predmet'),
(4,13,5,1,'','2.MI','7V','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(4,13,1,1,'','2.MI','7V','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(4,13,4,3,'','2.MI','BJ','','BJ','','Technické kreslení','UZS4A','','IT2','IT2','',NULL,'predmet'),
(4,13,1,10,'','1.MI','FY','','FY','','Technologie','UZS4O','','IT2','IT2','',NULL,'predmet'),
(4,13,3,6,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BK','BK','',NULL,'predmet'),
(4,13,3,7,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BK','BK','',NULL,'predmet'),
(4,13,3,8,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BK','BK','',NULL,'predmet'),
(4,13,4,6,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BA','BA','',NULL,'predmet'),
(4,13,4,7,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BA','BA','',NULL,'predmet'),
(4,13,4,8,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BA','BA','',NULL,'predmet'),
(4,13,2,1,'','1.MI','FE','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,2,2,'','1.MI','FE','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,2,7,'','1.MI','FE','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(4,13,1,8,'','1.MI','FE','','','','Chemie','U2XC7','','','','',NULL,'predmet'),
(4,13,1,5,'','1.MI','FE','','','','Informační a multimediální technologie','UMS61','','IT5','IT5','',NULL,'predmet'),
(4,13,1,6,'','1.MI','FE','','','','Informační a multimediální technologie','UMS61','','IT5','IT5','',NULL,'predmet'),
(4,13,4,9,'','1.MI','FZ','','FZ','','Fotografie','U0SAC','','BPG','BPG','',NULL,'predmet'),
(4,13,4,10,'','1.MI','FZ','','FZ','','Fotografie','U0SAC','','BPG','BPG','',NULL,'predmet'),
(4,13,3,2,'','1.MI','FE','','','','Marketingová komunikace','UPS70','','','','',NULL,'predmet'),
(4,13,4,2,'','1.MI','FE','','','','Dějiny umění','UPS70','','51','51','',NULL,'predmet'),
(4,13,3,4,'','1.MI','FE','','','','Dějiny umění','UPS70','','51','51','',NULL,'predmet'),
(4,13,5,5,'','1.MI','FY','','FY','','Prostorová tvorba','UZS4O','','BD1','BD1','',NULL,'predmet'),
(4,13,5,6,'','1.MI','FY','','FY','','Prostorová tvorba','UZS4O','','BD1','BD1','',NULL,'predmet'),
(4,13,5,7,'','1.MI','FY','','FY','','Prostorová tvorba','UZS4O','','BD1','BD1','',NULL,'predmet'),
(4,13,4,9,'','1.MI','FY','','FY','','Prostorová tvorba','UZS4O','','BA','BA','',NULL,'predmet'),
(4,13,4,10,'','1.MI','FY','','FY','','Prostorová tvorba','UZS4O','','BA','BA','',NULL,'predmet'),
(4,13,3,8,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(4,13,3,9,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(4,13,3,10,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(4,13,5,5,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BK','BK','',NULL,'predmet'),
(4,13,5,6,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BK','BK','',NULL,'predmet'),
(4,13,5,7,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BK','BK','',NULL,'predmet'),
(4,13,4,4,'','1.MI','FZ','','FZ','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,4,5,'','1.MI','FZ','','FZ','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,4,6,'','1.MI','FZ','','FZ','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,2,9,'','1.MI','FE','','','','Fyzika','UZSA3','','','','',NULL,'predmet'),
(4,13,3,1,'','1.MI','FE','','','','Fyzika','UZSA3','','','','',NULL,'predmet'),
(4,13,2,5,'','1.MI','FZ','','FZ','','Scénáristika','UZS44','','IT2','IT2','',NULL,'predmet'),
(4,13,2,10,'','1.MI','FE','','','','Dějepis','UI7OD','','','','',NULL,'predmet'),
(4,13,1,9,'','1.MI','FE','','','','Dějepis','UI7OD','','','','',NULL,'predmet'),
(4,13,1,4,'','1.MI','FE','','','','Matematika','U0SAI','','','','',NULL,'predmet'),
(4,13,5,3,'','1.MI','FE','','','','Matematika','U0SAI','','','','',NULL,'predmet'),
(4,13,1,1,'','1.MI','FY','','FY','','Technické kreslení','UZS4A','','IT2','IT2','',NULL,'predmet'),
(4,13,1,2,'','1.MI','FY','','FY','','Technické kreslení','UZS4A','','IT2','IT2','',NULL,'predmet');
DELETE FROM tenant.rozvrh_bunka WHERE verze_id=5;
INSERT INTO tenant.rozvrh_bunka (verze_id,tenant_id,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok) SELECT 5,13,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok FROM tenant.rozvrh_bunka WHERE verze_id=4 AND blok IN ('jazyky','tv');
INSERT INTO tenant.rozvrh_bunka (verze_id,tenant_id,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok) VALUES
(5,13,4,9,'','4.GD','T9','','','','Technologie','UZS4C','','BD1','BD1','',NULL,'predmet'),
(5,13,4,10,'','4.GD','T9','','','','Technologie','UZS4C','','BD1','BD1','',NULL,'predmet'),
(5,13,3,1,'','4.GD','T9','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(5,13,3,2,'','4.GD','T9','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(5,13,5,1,'','4.GD','XD','','XD','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(5,13,3,5,'','4.GD','XE','','XE','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(5,13,5,4,'','4.GD','T9','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,4,1,'','4.GD','T9','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,1,1,'','4.GD','T9','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,3,9,'','4.GD','XD','','XD','','Web design','UMS61','','BŠ','BŠ','',NULL,'predmet'),
(5,13,3,10,'','4.GD','XD','','XD','','Web design','UMS61','','BŠ','BŠ','',NULL,'predmet'),
(5,13,1,3,'','4.GD','XD','','XD','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(5,13,3,6,'','4.GD','XE','','XE','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(5,13,3,7,'','4.GD','XE','','XE','','Web design','UMS61','','IT2','IT2','',NULL,'predmet'),
(5,13,1,7,'','4.GD','XE','','XE','','Web design','UMS61','','MM','MM','',NULL,'predmet'),
(5,13,5,5,'','4.GD','T9','','','','Ekonomika a management','UNS6O','','','','',NULL,'predmet'),
(5,13,2,1,'','4.GD','T9','','','','Ekonomika a management','UNS6O','','','','',NULL,'predmet'),
(5,13,3,8,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(5,13,3,9,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(5,13,3,10,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(5,13,3,5,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BPG','BPG','',NULL,'predmet'),
(5,13,3,6,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BPG','BPG','',NULL,'predmet'),
(5,13,3,7,'','4.GD','D3','','D3','','Grafický design a navrhování','UTS88','','BPG','BPG','',NULL,'predmet'),
(5,13,1,8,'','4.GD','D4','','D4','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(5,13,1,9,'','4.GD','D4','','D4','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(5,13,1,10,'','4.GD','D4','','D4','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(5,13,3,8,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(5,13,3,9,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(5,13,3,10,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BPG','BPG','',NULL,'predmet'),
(5,13,3,5,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BŠ','BŠ','',NULL,'predmet'),
(5,13,3,6,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BŠ','BŠ','',NULL,'predmet'),
(5,13,3,7,'','4.GD','D5','','D5','','Grafický design a navrhování','UXS9D','','BŠ','BŠ','',NULL,'predmet'),
(5,13,1,8,'','4.GD','D6','','D6','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(5,13,1,9,'','4.GD','D6','','D6','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(5,13,1,10,'','4.GD','D6','','D6','','Grafický design a navrhování','UTS88','','BNA','BNA','',NULL,'predmet'),
(5,13,1,9,'','4.GD','XD','','XD','','Výtvarná tvorba','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,1,10,'','4.GD','XD','','XD','','Výtvarná tvorba','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,2,9,'','4.GD','XE','','XE','','Výtvarná tvorba','UOS6W','','BK','BK','',NULL,'predmet'),
(5,13,2,10,'','4.GD','XE','','XE','','Výtvarná tvorba','UOS6W','','BK','BK','',NULL,'predmet'),
(5,13,3,5,'','4.GD','XD','','XD','','Motion design','U0SAL','','BNA','BNA','',NULL,'predmet'),
(5,13,3,6,'','4.GD','XD','','XD','','Motion design','U0SAL','','BNA','BNA','',NULL,'predmet'),
(5,13,3,7,'','4.GD','XD','','XD','','Motion design','U0SAL','','BNA','BNA','',NULL,'predmet'),
(5,13,4,8,'','3.GD','5P','','5P','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,4,9,'','3.GD','5P','','5P','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,4,10,'','3.GD','5P','','5P','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,3,8,'','3.GD','5Q','','5Q','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,3,9,'','3.GD','5Q','','5Q','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,3,10,'','3.GD','5Q','','5Q','','Figurální kresba','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,3,1,'','3.GD','0M','','','','Český jazyk a literatura','URS7L','','','','',NULL,'predmet'),
(5,13,3,2,'','3.GD','0M','','','','Český jazyk a literatura','URS7L','','','','',NULL,'predmet'),
(5,13,1,1,'','3.GD','0M','','','','Český jazyk a literatura','URS7L','','','','',NULL,'predmet'),
(5,13,2,6,'','3.GD','5P','','5P','','Počítačová grafika','UXS9D','','BNA','BNA','',NULL,'predmet'),
(5,13,2,7,'','3.GD','5P','','5P','','Počítačová grafika','UXS9D','','BNA','BNA','',NULL,'predmet'),
(5,13,2,8,'','3.GD','5P','','5P','','Počítačová grafika','UXS9D','','BNA','BNA','',NULL,'predmet'),
(5,13,2,1,'','3.GD','5Q','','5Q','','Počítačová grafika','UXS9D','','IT2','IT2','',NULL,'predmet'),
(5,13,2,2,'','3.GD','5Q','','5Q','','Počítačová grafika','UXS9D','','IT2','IT2','',NULL,'predmet'),
(5,13,2,3,'','3.GD','5Q','','5Q','','Počítačová grafika','UXS9D','','IT2','IT2','',NULL,'predmet'),
(5,13,4,2,'','3.GD','0M','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,5,6,'','3.GD','0M','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,1,4,'','3.GD','0M','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,5,1,'','3.GD','5P','','5P','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,5,2,'','3.GD','5P','','5P','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,2,5,'','3.GD','5Q','','5Q','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,2,6,'','3.GD','5Q','','5Q','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,3,8,'','3.GD','5P','','5P','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(5,13,3,9,'','3.GD','5P','','5P','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(5,13,3,10,'','3.GD','5P','','5P','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(5,13,4,4,'','3.GD','5P','','5P','','Motion design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(5,13,4,5,'','3.GD','5P','','5P','','Motion design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(5,13,5,2,'','3.GD','5Q','','5Q','','Motion design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(5,13,5,3,'','3.GD','5Q','','5Q','','Motion design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(5,13,4,4,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,4,5,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,2,2,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,2,3,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,2,5,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,2,6,'','3.GD','KB','','KB','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,2,9,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,2,10,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,5,1,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,5,2,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,2,7,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,2,8,'','3.GD','KC','','KC','','5A','UZS4C','','','','',NULL,'predmet'),
(5,13,3,4,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,3,5,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,3,9,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,3,10,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,2,5,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,2,6,'','3.GD','KD','','KD','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,2,9,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,2,10,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,2,7,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,2,8,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,3,7,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,3,8,'','3.GD','KE','','KE','','5B','UOS6U','','','','',NULL,'predmet'),
(5,13,1,8,'','3.GD','0M','','','','Občanská nauka','UBHJ6','','','','',NULL,'predmet'),
(5,13,4,1,'','3.GD','0M','','','','Občanská nauka','UBHJ6','','','','',NULL,'predmet'),
(5,13,2,1,'','3.GD','5P','','5P','','Písmo','UOS6U','','BŠ','BŠ','',NULL,'predmet'),
(5,13,2,2,'','3.GD','5P','','5P','','Písmo','UOS6U','','BŠ','BŠ','',NULL,'predmet'),
(5,13,4,9,'','3.GD','5Q','','5Q','','Písmo','UOS6U','','BD4','BD4','',NULL,'predmet'),
(5,13,4,10,'','3.GD','5Q','','5Q','','Písmo','UOS6U','','BD4','BD4','',NULL,'predmet'),
(5,13,1,8,'','2.GD','BG','','BG','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(5,13,1,9,'','2.GD','BG','','BG','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(5,13,1,10,'','2.GD','BG','','BG','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(5,13,1,8,'','2.GD','BF','','BF','','Prostorový design','UOS6X','','BD4','BD4','',NULL,'predmet'),
(5,13,1,9,'','2.GD','BF','','BF','','Prostorový design','UOS6X','','BD4','BD4','',NULL,'predmet'),
(5,13,1,10,'','2.GD','BF','','BF','','Prostorový design','UOS6X','','BD4','BD4','',NULL,'predmet'),
(5,13,3,10,'','2.GD','7S','','','','Základy ekologie a biologie','U9TI4','','','','',NULL,'predmet'),
(5,13,4,6,'','2.GD','7S','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(5,13,4,7,'','2.GD','7S','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(5,13,1,1,'','2.GD','7S','','','','Český jazyk a literatura','UBHJ6','','','','',NULL,'predmet'),
(5,13,5,2,'','2.GD','7S','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,2,2,'','2.GD','7S','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,4,3,'','2.GD','7S','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,1,6,'','2.GD','BF','','BF','','Digitální fotografie','UUS8F','','BŠ','BŠ','',NULL,'predmet'),
(5,13,1,7,'','2.GD','BF','','BF','','Digitální fotografie','UUS8F','','BŠ','BŠ','',NULL,'predmet'),
(5,13,5,5,'','2.GD','BG','','BG','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,5,6,'','2.GD','BG','','BG','','Digitální fotografie','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,1,6,'','2.GD','BG','','BG','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(5,13,1,7,'','2.GD','BG','','BG','','Grafické umělecké techniky','UZS4C','','BD4','BD4','',NULL,'predmet'),
(5,13,5,1,'','2.GD','7S','','','','Dějiny grafického designu','UPS70','','','','',NULL,'predmet'),
(5,13,3,9,'','2.GD','7S','','','','Občanská nauka','USNKF','','','','',NULL,'predmet'),
(5,13,3,3,'','2.GD','7S','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(5,13,1,3,'','2.GD','7S','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(5,13,2,9,'','2.GD','BF','','BF','','Písmo','UXS9D','','BD4','BD4','',NULL,'predmet'),
(5,13,2,10,'','2.GD','BF','','BF','','Písmo','UXS9D','','BD4','BD4','',NULL,'predmet'),
(5,13,2,9,'','2.GD','BG','','BG','','Písmo','UTS88','','BD1','BD1','',NULL,'predmet'),
(5,13,2,10,'','2.GD','BG','','BG','','Písmo','UTS88','','BD1','BD1','',NULL,'predmet'),
(5,13,2,2,'','1.GD','FW','','FW','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(5,13,2,3,'','1.GD','FW','','FW','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(5,13,2,4,'','1.GD','FW','','FW','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(5,13,3,5,'','1.GD','FX','','FX','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(5,13,3,6,'','1.GD','FX','','FX','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(5,13,3,7,'','1.GD','FX','','FX','','Prostorový design','UNS6G','','BD4','BD4','',NULL,'predmet'),
(5,13,1,8,'','1.GD','FW','','FW','','Písmo a typografie','UNS6G','','BŠ','BŠ','',NULL,'predmet'),
(5,13,1,9,'','1.GD','FW','','FW','','Písmo a typografie','UNS6G','','BŠ','BŠ','',NULL,'predmet'),
(5,13,1,10,'','1.GD','FW','','FW','','Písmo a typografie','UNS6G','','BŠ','BŠ','',NULL,'predmet'),
(5,13,3,8,'','1.GD','FX','','FX','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(5,13,3,9,'','1.GD','FX','','FX','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(5,13,3,10,'','1.GD','FX','','FX','','Písmo a typografie','UNS6G','','BD1','BD1','',NULL,'predmet'),
(5,13,3,5,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BK','BK','',NULL,'predmet'),
(5,13,3,6,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BK','BK','',NULL,'predmet'),
(5,13,3,7,'','1.GD','FW','','FW','','Výtvarná příprava','UOS6W','','BK','BK','',NULL,'predmet'),
(5,13,2,4,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,2,5,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,2,6,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,2,1,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,2,2,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,2,3,'','1.GD','FX','','FX','','Výtvarná příprava','UOS6W','','BA','BA','',NULL,'predmet'),
(5,13,3,1,'','1.GD','FB','','','','Český jazyk a literatura','U0SAM','','','','',NULL,'predmet'),
(5,13,3,2,'','1.GD','FB','','','','Český jazyk a literatura','U0SAM','','','','',NULL,'predmet'),
(5,13,4,7,'','1.GD','FB','','','','Český jazyk a literatura','U0SAM','','','','',NULL,'predmet'),
(5,13,2,5,'','1.GD','FW','','FW','','Počítačová grafika','UNS6G','','BŠ','BŠ','',NULL,'predmet'),
(5,13,2,6,'','1.GD','FW','','FW','','Počítačová grafika','UNS6G','','BŠ','BŠ','',NULL,'predmet'),
(5,13,5,3,'','1.GD','FX','','FX','','Počítačová grafika','UNS6G','','MM','MM','',NULL,'predmet'),
(5,13,5,4,'','1.GD','FX','','FX','','Počítačová grafika','UNS6G','','MM','MM','',NULL,'predmet'),
(5,13,4,9,'','1.GD','FB','','','','Chemie','U2XC7','','','','',NULL,'predmet'),
(5,13,1,1,'','1.GD','FB','','','','Informační a multimediální technologie','UMS61','','IT5','IT5','',NULL,'predmet'),
(5,13,1,2,'','1.GD','FB','','','','Informační a multimediální technologie','UMS61','','IT5','IT5','',NULL,'predmet'),
(5,13,4,6,'','1.GD','FB','','','','Marketingová komunikace','UPS70','','','','',NULL,'predmet'),
(5,13,4,4,'','1.GD','FB','','','','Dějiny umění','UPS70','','51','51','',NULL,'predmet'),
(5,13,5,5,'','1.GD','FB','','','','Dějiny umění','UPS70','','51','51','',NULL,'predmet'),
(5,13,5,7,'','1.GD','FB','','','','Fyzika','UZSA3','','','','',NULL,'predmet'),
(5,13,4,8,'','1.GD','FB','','','','Fyzika','UZSA3','','','','',NULL,'predmet'),
(5,13,2,9,'','1.GD','FB','','','','Dějepis','UI7OD','','','','',NULL,'predmet'),
(5,13,4,10,'','1.GD','FB','','','','Dějepis','UI7OD','','','','',NULL,'predmet'),
(5,13,4,2,'','1.GD','FB','','','','Matematika','UZSA3','','','','',NULL,'predmet'),
(5,13,1,4,'','1.GD','FB','','','','Matematika','UZSA3','','','','',NULL,'predmet'),
(5,13,3,9,'','4.MI','XF','','XF','','Technologie','UZS4A','','IT2','IT2','',NULL,'predmet'),
(5,13,3,10,'','4.MI','XF','','XF','','Technologie','UZS4A','','IT2','IT2','',NULL,'predmet'),
(5,13,1,7,'','4.MI','XF','','XF','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,1,6,'','4.MI','XG','','XG','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,5,1,'','4.MI','TF','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(5,13,2,1,'','4.MI','TF','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(5,13,3,2,'','4.MI','TF','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(5,13,1,9,'','4.MI','TF','','','','Ekonomika a management','UNS6O','','','','',NULL,'predmet'),
(5,13,2,9,'','4.MI','XF','','XF','','3D vizualizace','UZS4A','','BŠ','BŠ','',NULL,'predmet'),
(5,13,2,10,'','4.MI','XF','','XF','','3D vizualizace','UZS4A','','BŠ','BŠ','',NULL,'predmet'),
(5,13,4,8,'','4.MI','XF','','XF','','Design nábytku','UVS8S','','D','D','',NULL,'predmet'),
(5,13,4,9,'','4.MI','XF','','XF','','Design nábytku','UVS8S','','D','D','',NULL,'predmet'),
(5,13,4,10,'','4.MI','XF','','XF','','Design nábytku','UVS8S','','D','D','',NULL,'predmet'),
(5,13,2,9,'','4.MI','XG','','XG','','Web design a multimediální aplikace','UMS61','','BPG','BPG','',NULL,'predmet'),
(5,13,2,10,'','4.MI','XG','','XG','','Web design a multimediální aplikace','UMS61','','BPG','BPG','',NULL,'predmet'),
(5,13,4,8,'','4.MI','EA','','EA','','Animace 2','UZS44','','MM','MM','',NULL,'predmet'),
(5,13,4,9,'','4.MI','EA','','EA','','Animace 2','UZS44','','MM','MM','',NULL,'predmet'),
(5,13,4,10,'','4.MI','EA','','EA','','Animace 2','UZS44','','MM','MM','',NULL,'predmet'),
(5,13,2,8,'','4.MI','EA','','EA','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(5,13,2,9,'','4.MI','EA','','EA','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(5,13,2,10,'','4.MI','EA','','EA','','Animace 2','UZS44','','IT2','IT2','',NULL,'predmet'),
(5,13,1,3,'','4.MI','TF','','','','Matematika','UZS4V','','','','',NULL,'predmet'),
(5,13,4,1,'','4.MI','TF','','','','Matematika','UZS4V','','','','',NULL,'predmet'),
(5,13,3,8,'','3.MI','5R','','5R','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(5,13,3,9,'','3.MI','5R','','5R','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(5,13,3,10,'','3.MI','5R','','5R','','Figurální kresba','USS80','','BK','BK','',NULL,'predmet'),
(5,13,5,5,'','3.MI','5R','','5R','','Technologie','USS80','','IT2','IT2','',NULL,'predmet'),
(5,13,5,6,'','3.MI','5R','','5R','','Technologie','USS80','','IT2','IT2','',NULL,'predmet'),
(5,13,4,1,'','3.MI','0P','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,2,9,'','3.MI','5S','','5S','','Počítačová grafika','UPS70','','BNA','BNA','',NULL,'predmet'),
(5,13,2,10,'','3.MI','5S','','5S','','Počítačová grafika','UPS70','','BNA','BNA','',NULL,'predmet'),
(5,13,1,3,'','3.MI','0P','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(5,13,3,1,'','3.MI','0P','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(5,13,4,5,'','3.MI','0P','','','','Dějiny umění','USS80','','51','51','',NULL,'predmet'),
(5,13,4,8,'','3.MI','5R','','5R','','3D vizualizace','UZS4A','','BŠ','BŠ','',NULL,'predmet'),
(5,13,4,9,'','3.MI','5R','','5R','','3D vizualizace','UZS4A','','BŠ','BŠ','',NULL,'predmet'),
(5,13,4,10,'','3.MI','5R','','5R','','3D vizualizace','UZS4A','','BŠ','BŠ','',NULL,'predmet'),
(5,13,3,3,'','3.MI','5R','','5R','','Konstrukční příprava','UZS4O','','D','D','',NULL,'predmet'),
(5,13,3,4,'','3.MI','5R','','5R','','Konstrukční příprava','UZS4O','','D','D','',NULL,'predmet'),
(5,13,3,5,'','3.MI','5R','','5R','','Konstrukční příprava','UZS4O','','D','D','',NULL,'predmet'),
(5,13,2,8,'','3.MI','5R','','5R','','Design interieru a navrhování','UVS8S','','BA','BA','',NULL,'predmet'),
(5,13,2,9,'','3.MI','5R','','5R','','Design interieru a navrhování','UVS8S','','BA','BA','',NULL,'predmet'),
(5,13,2,10,'','3.MI','5R','','5R','','Design interieru a navrhování','UVS8S','','BA','BA','',NULL,'predmet'),
(5,13,3,3,'','3.MI','5S','','5S','','3D Animace','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,3,4,'','3.MI','5S','','5S','','3D Animace','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,3,5,'','3.MI','5S','','5S','','3D Animace','UUS8F','','MM','MM','',NULL,'predmet'),
(5,13,5,6,'','3.MI','5S','','5S','','Web design a multimediální aplikace','UMS61','','BPG','BPG','',NULL,'predmet'),
(5,13,5,7,'','3.MI','5S','','5S','','Web design a multimediální aplikace','UMS61','','BPG','BPG','',NULL,'predmet'),
(5,13,2,8,'','3.MI','5S','','5S','','Web design a multimediální aplikace','UMS61','','BŠ','BŠ','',NULL,'predmet'),
(5,13,4,8,'','3.MI','KF','','KF','','Game design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(5,13,4,9,'','3.MI','KF','','KF','','Game design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(5,13,4,10,'','3.MI','KF','','KF','','Game design','UZSA4','','IT2','IT2','',NULL,'predmet'),
(5,13,2,8,'','3.MI','KF','','KF','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(5,13,2,9,'','3.MI','KF','','KF','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(5,13,2,10,'','3.MI','KF','','KF','','Game design','UZSA4','','MM','MM','',NULL,'predmet'),
(5,13,1,8,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','IT2','IT2','',NULL,'predmet'),
(5,13,1,9,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','IT2','IT2','',NULL,'predmet'),
(5,13,1,10,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','IT2','IT2','',NULL,'predmet'),
(5,13,3,8,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','MM','MM','',NULL,'predmet'),
(5,13,3,9,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','MM','MM','',NULL,'predmet'),
(5,13,3,10,'','3.MI','KG','','KG','','Audiovizuální tvorba 2','UUS8I','','MM','MM','',NULL,'predmet'),
(5,13,1,8,'','3.MI','KF','','KF','','Animace 2','UZS44','','MM','MM','',NULL,'predmet'),
(5,13,1,9,'','3.MI','KF','','KF','','Animace 2','UZS44','','MM','MM','',NULL,'predmet'),
(5,13,1,10,'','3.MI','KF','','KF','','Animace 2','UZS44','','MM','MM','',NULL,'predmet'),
(5,13,3,3,'','3.MI','KG','','KG','','Fotografie 2','U0SAC','','IT2','IT2','',NULL,'predmet'),
(5,13,3,4,'','3.MI','KG','','KG','','Fotografie 2','U0SAC','','IT2','IT2','',NULL,'predmet'),
(5,13,3,5,'','3.MI','KG','','KG','','Fotografie 2','U0SAC','','IT2','IT2','',NULL,'predmet'),
(5,13,5,1,'','3.MI','0P','','','','Občanská nauka','UZS4A','','','','',NULL,'predmet'),
(5,13,1,1,'','3.MI','0P','','','','Občanská nauka','UZS4A','','','','',NULL,'predmet'),
(5,13,2,1,'','3.MI','0P','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(5,13,4,3,'','3.MI','0P','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(5,13,4,6,'','2.MI','BJ','','BJ','','Technologie','USS80','','MM','MM','',NULL,'predmet'),
(5,13,3,9,'','2.MI','7V','','','','Základy ekologie a biologie','U9TI4','','','','',NULL,'predmet'),
(5,13,3,2,'','2.MI','7V','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,3,3,'','2.MI','7V','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,3,6,'','2.MI','7V','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,1,6,'','2.MI','7V','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,4,7,'','2.MI','7V','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,2,5,'','2.MI','7V','','','','Dějiny umění','UUS8D','','51','51','',NULL,'predmet'),
(5,13,1,8,'','2.MI','BJ','','BJ','','Prostorová tvorba','UZS4O','','BD1','BD1','',NULL,'predmet'),
(5,13,1,9,'','2.MI','BJ','','BJ','','Prostorová tvorba','UZS4O','','BD1','BD1','',NULL,'predmet'),
(5,13,1,10,'','2.MI','BJ','','BJ','','Prostorová tvorba','UZS4O','','BD1','BD1','',NULL,'predmet'),
(5,13,2,8,'','2.MI','BJ','','BJ','','Konstrukční příprava','USS80','','D','D','',NULL,'predmet'),
(5,13,2,9,'','2.MI','BJ','','BJ','','Konstrukční příprava','USS80','','D','D','',NULL,'predmet'),
(5,13,2,10,'','2.MI','BJ','','BJ','','Konstrukční příprava','USS80','','D','D','',NULL,'predmet'),
(5,13,4,6,'','2.MI','BI','','BI','','Scénáristika','UUS8I','','IT2','IT2','',NULL,'predmet'),
(5,13,4,3,'','2.MI','BJ','','BJ','','Dějiny designu','UZS4A','','','','',NULL,'predmet'),
(5,13,4,3,'','2.MI','BI','','BI','','Dějiny multimedií','UMS61','','','','',NULL,'predmet'),
(5,13,4,9,'','2.MI','BI','','BI','','5F','UUS8F','','','','',NULL,'predmet'),
(5,13,4,10,'','2.MI','BI','','BI','','5F','UUS8F','','','','',NULL,'predmet'),
(5,13,2,10,'','2.MI','BI','','BI','','5F','UUS8F','','','','',NULL,'predmet'),
(5,13,1,9,'','2.MI','BI','','BI','','5G','U0SAJ','','','','',NULL,'predmet'),
(5,13,1,10,'','2.MI','BI','','BI','','5G','U0SAJ','','','','',NULL,'predmet'),
(5,13,1,1,'','2.MI','7V','','','','Občanská nauka','USNKF','','','','',NULL,'predmet'),
(5,13,4,1,'','2.MI','7V','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(5,13,5,1,'','2.MI','7V','','','','Matematika','UDC5V','','','','',NULL,'predmet'),
(5,13,1,3,'','2.MI','BJ','','BJ','','Technické kreslení','UZS4A','','MM','MM','',NULL,'predmet'),
(5,13,3,2,'','1.MI','FY','','FY','','Technologie','UZS4O','','MM','MM','',NULL,'predmet'),
(5,13,4,5,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BA','BA','',NULL,'predmet'),
(5,13,4,6,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BA','BA','',NULL,'predmet'),
(5,13,4,7,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BA','BA','',NULL,'predmet'),
(5,13,5,5,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BK','BK','',NULL,'predmet'),
(5,13,5,6,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BK','BK','',NULL,'predmet'),
(5,13,5,7,'','1.MI','FY','','FY','','Výtvarná příprava','UOS6X','','BK','BK','',NULL,'predmet'),
(5,13,1,1,'','1.MI','FE','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,1,2,'','1.MI','FE','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,2,1,'','1.MI','FE','','','','Český jazyk a literatura','UNS6M','','','','',NULL,'predmet'),
(5,13,4,8,'','1.MI','FZ','','FZ','','Počítačová grafika','UPS70','','BPG','BPG','',NULL,'predmet'),
(5,13,4,9,'','1.MI','FZ','','FZ','','Počítačová grafika','UPS70','','BPG','BPG','',NULL,'predmet'),
(5,13,4,10,'','1.MI','FZ','','FZ','','Počítačová grafika','UPS70','','BPG','BPG','',NULL,'predmet'),
(5,13,2,9,'','1.MI','FE','','','','Chemie','U2XC7','','','','',NULL,'predmet'),
(5,13,1,9,'','1.MI','FE','','','','Informační a multimediální technologie','UMS61','','IT5','IT5','',NULL,'predmet'),
(5,13,1,10,'','1.MI','FE','','','','Informační a multimediální technologie','UMS61','','IT5','IT5','',NULL,'predmet'),
(5,13,4,6,'','1.MI','FZ','','FZ','','Fotografie','U0SAC','','BPG','BPG','',NULL,'predmet'),
(5,13,4,7,'','1.MI','FZ','','FZ','','Fotografie','U0SAC','','BPG','BPG','',NULL,'predmet'),
(5,13,2,6,'','1.MI','FE','','','','Marketingová komunikace','UPS70','','','','',NULL,'predmet'),
(5,13,2,7,'','1.MI','FE','','','','Dějiny umění','UPS70','','51','51','',NULL,'predmet'),
(5,13,5,3,'','1.MI','FE','','','','Dějiny umění','UPS70','','51','51','',NULL,'predmet'),
(5,13,4,8,'','1.MI','FY','','FY','','Prostorová tvorba','UZS4O','','BK','BK','',NULL,'predmet'),
(5,13,4,9,'','1.MI','FY','','FY','','Prostorová tvorba','UZS4O','','BK','BK','',NULL,'predmet'),
(5,13,4,10,'','1.MI','FY','','FY','','Prostorová tvorba','UZS4O','','BK','BK','',NULL,'predmet'),
(5,13,3,5,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(5,13,3,6,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(5,13,3,7,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(5,13,5,5,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(5,13,5,6,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(5,13,5,7,'','1.MI','FZ','','FZ','','Výtvarná příprava pro média','UZS44','','BA','BA','',NULL,'predmet'),
(5,13,1,5,'','1.MI','FZ','','FZ','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(5,13,1,6,'','1.MI','FZ','','FZ','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(5,13,1,7,'','1.MI','FZ','','FZ','','Animace','UZS44','','IT2','IT2','',NULL,'predmet'),
(5,13,1,8,'','1.MI','FE','','','','Fyzika','UZSA3','','','','',NULL,'predmet'),
(5,13,3,9,'','1.MI','FE','','','','Fyzika','UZSA3','','','','',NULL,'predmet'),
(5,13,4,4,'','1.MI','FZ','','FZ','','Scénáristika','UZS44','','MM','MM','',NULL,'predmet'),
(5,13,2,10,'','1.MI','FE','','','','Dějepis','UI7OD','','','','',NULL,'predmet'),
(5,13,3,10,'','1.MI','FE','','','','Dějepis','UI7OD','','','','',NULL,'predmet'),
(5,13,4,2,'','1.MI','FE','','','','Matematika','U0SAI','','','','',NULL,'predmet'),
(5,13,2,2,'','1.MI','FE','','','','Matematika','U0SAI','','','','',NULL,'predmet'),
(5,13,3,6,'','1.MI','FY','','FY','','Technické kreslení','UZS4A','','MM','MM','',NULL,'predmet'),
(5,13,3,7,'','1.MI','FY','','FY','','Technické kreslení','UZS4A','','MM','MM','',NULL,'predmet');