DELETE FROM tenant.rozvrh_bunka WHERE tenant_id=13 AND verze_id IN (4,5,6,7) AND blok='tv';
INSERT INTO tenant.rozvrh_bunka (verze_id,tenant_id,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok) VALUES
(4,13,1,9,'','2.L','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,10,'','2.L','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,9,'','2.CR','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,10,'','2.CR','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,9,'','2.O','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,10,'','2.O','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,9,'','1.G','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,10,'','1.G','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,9,'','1.I','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,10,'','1.I','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,9,'','1.J','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,10,'','1.J','','TV-XX','Kluci','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,4,9,'','4.VO','','TV-XY','Kluci','','Tělesná výchova','USNKF','','TV','TV','S',NULL,'tv'),
(4,13,4,10,'','4.VO','','TV-XY','Kluci','','Tělesná výchova','USNKF','','TV','TV','S',NULL,'tv'),
(4,13,4,9,'','4.ZO','','TV-XY','Kluci','','Tělesná výchova','USNKF','','TV','TV','S',NULL,'tv'),
(4,13,4,10,'','4.ZO','','TV-XY','Kluci','','Tělesná výchova','USNKF','','TV','TV','S',NULL,'tv'),
(4,13,4,9,'','3.ZO','','TV-XY','Kluci','','Tělesná výchova','USNKF','','TV','TV','S',NULL,'tv'),
(4,13,4,10,'','3.ZO','','TV-XY','Kluci','','Tělesná výchova','USNKF','','TV','TV','S',NULL,'tv'),
(4,13,2,1,'','1.G','','TV-2G-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','S',NULL,'tv'),
(4,13,2,2,'','1.G','','TV-2G-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','S',NULL,'tv'),
(4,13,1,1,'','2.L','','TV-28-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,1,2,'','2.L','','TV-28-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,2,9,'','2.O','','TV-2C-div','Dívky','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,2,10,'','2.O','','TV-2C-div','Dívky','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,3,1,'','1.J','','TV-2J-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,3,2,'','1.J','','TV-2J-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,3,9,'','3.ZO','','TV-24-div','Dívky','','Tělesná výchova','UYS9M','','TV','TV','S',NULL,'tv'),
(4,13,3,10,'','3.ZO','','TV-24-div','Dívky','','Tělesná výchova','UYS9M','','TV','TV','S',NULL,'tv'),
(4,13,3,9,'','4.ZO','','TV-1Z-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,3,10,'','4.ZO','','TV-1Z-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,2,1,'','1.I','','TV-2I-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,2,2,'','1.I','','TV-2I-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,2,9,'','2.CR','','TV-29-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','S',NULL,'tv'),
(4,13,2,10,'','2.CR','','TV-29-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','S',NULL,'tv'),
(4,13,4,9,'','4.VO','','TV-1Y-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,4,10,'','4.VO','','TV-1Y-div','Dívky','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,5,5,'','2.MI','','TV-2B-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','T',NULL,'tv'),
(4,13,5,6,'','2.MI','','TV-2B-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','T',NULL,'tv'),
(4,13,4,3,'','1.GD','','TV-2E-cela','Celá třída','','Tělesná výchova','USS81','','TV','TV','T',NULL,'tv'),
(4,13,4,4,'','1.GD','','TV-2E-cela','Celá třída','','Tělesná výchova','USS81','','TV','TV','T',NULL,'tv'),
(4,13,4,5,'','4.GD','','TV-1U-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','T',NULL,'tv'),
(4,13,4,6,'','4.GD','','TV-1U-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','T',NULL,'tv'),
(4,13,2,7,'','3.VO','','TV-23-cela','Celá třída','','Tělesná výchova','USS81','','TV','TV','S',NULL,'tv'),
(4,13,2,8,'','3.VO','','TV-23-cela','Celá třída','','Tělesná výchova','USS81','','TV','TV','S',NULL,'tv'),
(4,13,4,7,'','3.CR','','TV-22-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,4,8,'','3.CR','','TV-22-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','L',NULL,'tv'),
(4,13,3,5,'','2.GD','','TV-2A-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,3,6,'','2.GD','','TV-2A-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,2,5,'','3.MI','','TV-26-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,2,6,'','3.MI','','TV-26-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,2,3,'','1.MI','','TV-2F-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,2,4,'','1.MI','','TV-2F-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,1,9,'','4.CR','','TV-1T-cela','Celá třída','','Tělesná výchova','USS81','','TV','TV','S',NULL,'tv'),
(4,13,1,10,'','4.CR','','TV-1T-cela','Celá třída','','Tělesná výchova','USS81','','TV','TV','S',NULL,'tv'),
(4,13,3,7,'','4.MI','','TV-1W-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,3,8,'','4.MI','','TV-1W-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,3,3,'','3.A','','TV-21-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','S',NULL,'tv'),
(4,13,3,4,'','3.A','','TV-21-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','S',NULL,'tv'),
(4,13,5,3,'','1.D','','TV-2D-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,5,4,'','1.D','','TV-2D-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,3,'','3.B','','TV-20-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','S',NULL,'tv'),
(4,13,1,4,'','3.B','','TV-20-cela','Celá třída','','Tělesná výchova','UPS75','','TV','TV','S',NULL,'tv'),
(4,13,1,7,'','2.A','','TV-27-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,1,8,'','2.A','','TV-27-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','L',NULL,'tv'),
(4,13,5,7,'','3.GD','','TV-25-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv'),
(4,13,5,8,'','3.GD','','TV-25-cela','Celá třída','','Tělesná výchova','USNKF','','TV','TV','T',NULL,'tv');
INSERT INTO tenant.rozvrh_bunka (verze_id,tenant_id,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok) SELECT 5,13,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok FROM tenant.rozvrh_bunka WHERE tenant_id=13 AND verze_id=4 AND blok='tv';
INSERT INTO tenant.rozvrh_bunka (verze_id,tenant_id,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok) SELECT 6,13,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok FROM tenant.rozvrh_bunka WHERE tenant_id=13 AND verze_id=4 AND blok='tv';
INSERT INTO tenant.rozvrh_bunka (verze_id,tenant_id,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok) SELECT 7,13,den,hodina,kod_trid,trida,kod_skup,kod_spoj,skup_zkr,kod_pred,pred,kod_ucit,ucitel,kod_mist,mist,kod_cykl,cj_uroven,blok FROM tenant.rozvrh_bunka WHERE tenant_id=13 AND verze_id=4 AND blok='tv';